---
# mysql cliを安全に、便利に、使いやすくするための設定ファイル
- name: Copy /etc/my.cnf.d/mysql-clients.cnf
  template:
    # 他のroleから、import_roleできるよう、フルパスにしています。
    # See. Ansibleで他のplaybookをincludeした際にpathが通らないとき - Qiita
    #     https://qiita.com/isobecky74/items/5b3b44f55f0f1dcda39c
    src: "{{ playbook_dir }}/roles/mariadb_client/templates/mysql-clients.cnf.j2"
    dest: /etc/my.cnf.d/mysql-clients.cnf
    owner: root
    group: root
    mode: 0644
  # Templateへ渡す変数
  vars:
    # MySQL client側のホスト名から、接続先DBサーバの接頭辞としてこの変数の値を生成し、Jinja2テンプレートへ渡します。
    # 例. client が "gooid-30-dev-hlp-201" のとき、この変数の値は "gooid-30-dev-mdb-20"
    # 例. client が "idhub-21-pro-web-003" のとき、この変数の値は "idhub-21-pro-mdb-00"
    db_hostname_prefix: "{{ inventory_hostname_short | regex_replace('^(?P<prefix>\\w+-\\w+-\\w+)-\\w+-(?P<num>\\d)\\d{2}$', '\\g<prefix>-mdb-\\g<num>') }}"
    # Jinja2 template側では、Dev/Proなどの環境で条件分岐して、接続先を定義します。
  when: server_role != 'bastion'

# bastionサーバー専用のmysql cli設定ファイル
- name: Copy /etc/my.cnf.d/mysql-clients.cnf
  template:
    src: "{{ playbook_dir }}/roles/mariadb_client/templates/mysql-clients.cnf.bastion.j2"
    dest: /etc/my.cnf.d/mysql-clients.cnf
    owner: root
    group: root
    mode: 0644
  when: server_role == 'bastion'
