FROM redmine:5.0.2

USER root

ENV http_proxy="{{ proxy_env.http_proxy }}"
ENV https_proxy="{{ proxy_env.http_proxy }}"
ENV HTTP_PROXY="{{ proxy_env.http_proxy }}"
ENV HTTPS_PROXY="{{ proxy_env.http_proxy }}"
ENV no_proxy="localhost,127.0.0.1"
ENV NO_PROXY="localhost,127.0.0.1"
ENV TZ=Asia/Tokyo

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# OSの更新: redmine 5 は Debian系Linux
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y unzip vim && \
    apt-get clean

# Setup
WORKDIR /usr/src/redmine
USER redmine

# Copy configuration files
COPY ./config/database.yml /usr/src/redmine/config/
COPY ./config/configuration.yml /usr/src/redmine/config/

# サブパス /ticket で運用する設定 (パッチ済み環境ファイル)
COPY ./config/environment.rb /usr/src/redmine/config/

# サブパス /ticket で運用する設定 (静的ファイルを public から public/ticket に移動)
RUN cp -a public ticket && mv ticket public/

# Extra gem for debug
RUN echo "gem 'pry-rails'" >> Gemfile
RUN bundle install

# Extra plugins
# redmine_code_review
RUN curl -s -S -L -o ./plugins/redmine_code_review-1.2.1.zip https://github.com/haru/redmine_code_review/releases/download/1.2.1/redmine_code_review-1.2.1.zip
RUN unzip ./plugins/redmine_code_review-1.2.1.zip -d ./plugins
RUN rm ./plugins/redmine_code_review-1.2.1.zip

# プラグインのマイグレーションが必要な場合、Redmine Pod 起動後にRedmineコンテナ内で以下のコマンドを実行する必要があります。
# podman exec -it redminepod-redmine rake redmine:plugins:migrate RAILS_ENV=production

# EOS
