---
- name: logユーザー用のホームディレクトリの作成
  file: path={{ item }} state=directory owner=log group=log mode=0700
  with_items:
  - /home/log

- name: log削除用configの配布先ディレクトリの作成
  file: path={{ item }} state=directory owner=log group=log mode=0755
  with_items:
  - /home/log/bin

- name: log削除用cronの配布
  template:
    src: templates/cron/log_delete.j2
    dest: /etc/cron.d/log_delete
    owner: root
    group: root
    mode: 0644

- name: log削除用scriptの配布
  copy:
    src: files/script/source_log_delete.sh
    dest: /home/log/source_log_delete.sh
    owner: log
    group: log
    mode: 0744

- name: gooid-webにおけるlog削除用configの配布
  copy:
    src: files/config/config_del_{{server_kinds}}
    dest: /home/log/bin/config_del_{{ inventory_hostname_short }}
    owner: log
    group: log
    mode: 0644
