---
# ディレクトリをループで作成する
- name: Create directories
  file: path={{ item }} state=directory owner=tomcat group=tomcat mode=0755
  loop:
  - /opt/gooidc-oidc
  - /opt/gooidc-oidc/bin
  - /opt/gooidc-oidc/logs

- name: Copy gooidc-oidc.service
  template:
    src: templates/gooidc-oidc.service.j2
    dest: /opt/gooidc-oidc/gooidc-oidc.service
    backup: yes 
    owner: tomcat
    group: tomcat
    mode: 0644

- name: Copy authman
  template:
    src: templates/authman.j2
    dest: /opt/gooidc-oidc/bin/authman
    backup: yes 
    owner: tomcat
    group: tomcat
    mode: 0755

- name: Copy gbs_sudoers
  template:
    src: templates/gbs_sudoers.j2
    dest: /etc/sudoers.d/gbs_sudoers
    backup: yes 
    owner: root
    group: root
    mode: 0440
