---
- name: create /db0 directory
  file:
    path: "/db0"
    state: directory
    owner: "root"
    group: "root"
    mode: "755"

# /db0/app
- name: gooid batch に必要な /db0/app/goo 配下のディレクトリを作成します。
  file:
    path: "{{ item.path }}"
    state: directory
    owner: gooscp
    group: gooscp
    mode: "{{ item.mode }}"
  loop:
  # 2024-11-13 利用していないDIRを精査し、本当に必要なDIRのみ列挙した。
  #
  # 確認した方法は以下の通り。
  # $ find /db0/app/goo/ -type f -mtime -365 | perl -pe 's|\/[^\/]+$|\n|g' | sort -u
  #    - 1年以内に更新された「あったかい」ファイルを保持しているディレクトリのみを列挙
  #
    - { path: /db0/app, mode: '0755', owner: 'root', group: 'root'}
    - { path: /db0/app/goo, mode: '0755' }
    - { path: /db0/app/goo/batch_file, mode: '0777' }
    - { path: /db0/app/goo/batch_file/COMMON, mode: '0755'}
    - { path: /db0/app/goo/batch_file/COMMON/hospitality, mode: '0755'}
    - { path: /db0/app/goo/batch_file/COMMON/point, mode: '0755'}
    - { path: /db0/app/goo/batch_file/COMMON/report, mode: '0755'}
    - { path: /db0/app/goo/batch_file/OSHIETE, mode: '0755'}
    - { path: /db0/app/goo/batch_file/OSHIETE/snd, mode: '0755'}
    - { path: /db0/app/goo/batch_file/gbs_history, mode: '0755'}
    - { path: /db0/app/goo/ipcheck, mode: '0755'}
    - { path: /db0/app/goo/ipcheck/log, mode: '0755'}

# /db0/app_gbs
- name: gbs batch に必要な /db0/app_gbs 配下のディレクトリを作成します。
  file:
    path: "{{ item.path }}"
    state: directory
    owner: gooscp
    group: gooscp
    mode: 0755
  loop:
    - { path: /db0/app_gbs }
    - { path: /db0/app_gbs/file }
    - { path: /db0/app_gbs/file/data }
    - { path: /db0/app_gbs/file/data/BatchBillingRequest_INPUT_005 }
    - { path: /db0/app_gbs/file/data/BatchBillingRequest_OUTPUT_001 }
    - { path: /db0/app_gbs/file/data/BatchBillingResultListDivide_OUTPUT_005 }
    - { path: /db0/app_gbs/file/data/BatchBillingResultListDivide_OUTPUT_005_in }
    - { path: /db0/app_gbs/file/data/BatchBillingResultUpdate_INPUT_001 }
    - { path: /db0/app_gbs/file/data/CardCleaning }
    - { path: /db0/app_gbs/file/data/CompulsionCancelList }
    - { path: /db0/app_gbs/file/data/CompulsionCancelList/output }
    - { path: /db0/app_gbs/file/data/CreateAutoContinueList_OUTPUT_001 }
    - { path: /db0/app_gbs/file/data/CreateAutoContinueList_OUTPUT_002 }
    - { path: /db0/app_gbs/file/data/CreateCompulsionCancelList_OUTPUT_001 }
    - { path: /db0/app_gbs/file/data/CreatePointFile_OUTPUT_001 }
    - { path: /db0/app_gbs/file/data/EntrepreneurAdjustment }
    - { path: /db0/app_gbs/file/data/EntrepreneurAdjustment/SalesInfo }
    - { path: /db0/app_gbs/file/data/EntrepreneurAdjustment/SalesInfo/output }
    - { path: /db0/app_gbs/file/data/EntrepreneurAdjustment/SalesInfo/send }
    - { path: /db0/app_gbs/file/data/EntrepreneurAdjustment/SalesInfo/send/accounting }
    - { path: /db0/app_gbs/file/data/EntrepreneurAdjustment/SalesInfo/send/nttf }
    - { path: /db0/app_gbs/file/data/EntrepreneurAdjustment/SalesInfo/send/service }
    - { path: /db0/app_gbs/file/data/EntrepreneurAdjustment/SalesInfo/send/service/euc }
    - { path: /db0/app_gbs/file/data/EntrepreneurAdjustment/SalesInfo/send/service/utf }
    - { path: /db0/app_gbs/file/data/EntrepreneurAdjustment/SalesInfo/service }
    - { path: /db0/app_gbs/file/data/EntrepreneurAdjustment/SalesInfo/service/euc }
    - { path: /db0/app_gbs/file/data/GiveServicePoint_INPUT_001 }
    - { path: /db0/app_gbs/file/data/GiveServicePoint_OUTPUT_001 }
    - { path: /db0/app_gbs/file/data/ObtainOrderResultFile_OUTPUT_005 }
    - { path: /db0/app_gbs/file/data/PointAdjustment }
    - { path: /db0/app_gbs/file/data/PointAdjustment/output }
    - { path: /db0/app_gbs/file/data/PointAdjustment_OUTPUT_001 }
    - { path: /db0/app_gbs/file/data/PreOrderCheck }
    - { path: /db0/app_gbs/file/data/ResignExtract_OUTPUT_001 }
    - { path: /db0/app_gbs/file/data/ResignNoticeList }
    - { path: /db0/app_gbs/file/data/SalesInfo_OUTPUT_001 }
    - { path: /db0/app_gbs/file/data/SalesNewsFlashD_OUTPUT_001 }
    - { path: /db0/app_gbs/file/data/SalesNewsFlashM_OUTPUT_001 }
    - { path: /db0/app_gbs/file/data/Save }
    - { path: /db0/app_gbs/file/data/Save/AdvanceInfo }
    - { path: /db0/app_gbs/file/data/Save/BatchBillingRequest_INPUT_005 }
    - { path: /db0/app_gbs/file/data/Save/BatchBillingRequest_OUTPUT_001 }
    - { path: /db0/app_gbs/file/data/Save/BatchBillingResultListDivide_OUTPUT_005 }
    - { path: /db0/app_gbs/file/data/Save/BatchBillingResultListDivide_OUTPUT_005_in }
    - { path: /db0/app_gbs/file/data/Save/BatchBillingResultUpdate_INPUT_001 }
    - { path: /db0/app_gbs/file/data/Save/CardCleaning }
    - { path: /db0/app_gbs/file/data/Save/CreateAutoContinueList_OUTPUT_001 }
    - { path: /db0/app_gbs/file/data/Save/CreateAutoContinueList_OUTPUT_002 }
    - { path: /db0/app_gbs/file/data/Save/CreateCompulsionCancelList_OUTPUT_001 }
    - { path: /db0/app_gbs/file/data/Save/CreateDirectoryTypeCompulsionCancelList_OUTPUT_001 }
    - { path: /db0/app_gbs/file/data/Save/CreatePointFile_OUTPUT_001 }
    - { path: /db0/app_gbs/file/data/Save/GiveServicePoint_INPUT_001 }
    - { path: /db0/app_gbs/file/data/Save/GiveServicePoint_OUTPUT_001 }
    - { path: /db0/app_gbs/file/data/Save/OrderRequestListConfirm_INPUT_005 }
    - { path: /db0/app_gbs/file/data/Save/OrderRequestListConfirm_INPUT_005_next }
    - { path: /db0/app_gbs/file/data/Save/PointAdjustment_OUTPUT_001 }
    - { path: /db0/app_gbs/file/data/Save/PreOrderCheck }
    - { path: /db0/app_gbs/file/data/Save/ResignExtract_OUTPUT_001 }
    - { path: /db0/app_gbs/file/data/Save/SalesInfo_OUTPUT_001 }
    - { path: /db0/app_gbs/file/data/Save/SalesInfo_OUTPUT_001/accounting }
    - { path: /db0/app_gbs/file/data/Save/SalesInfo_OUTPUT_001/nttf }
    - { path: /db0/app_gbs/file/data/Save/SalesInfo_OUTPUT_001/service }
    - { path: /db0/app_gbs/file/data/Save/SalesNewsFlashD_OUTPUT_001 }
    - { path: /db0/app_gbs/file/data/Save/SalesNewsFlashM_OUTPUT_001 }
    - { path: /db0/app_gbs/file/data/Save/SendMail }
    - { path: /db0/app_gbs/file/data/Save/SendMail_DirectoryType }
    - { path: /db0/app_gbs/file/data/Save1 }
    - { path: /db0/app_gbs/file/data/Save1/BatchBillingRequest_INPUT_005 }
    - { path: /db0/app_gbs/file/data/SendMail }
    - { path: /db0/app_gbs/file/data/lock }
