[project]
name = "aws-ses-not-dns-auto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.40.21",
    "cfn-lint>=1.39.1",
    "click>=8.2.1",
    "pyyaml>=6.0.2",
    "sceptre>=4.5.3",
]
