---

- name: ensure LCM_templates dir is created
  file:
    path: "{{ es_conf_dir }}/templates/{{ item }}"
    state: directory
    owner: root
    group: elasticsearch
    mode: "2750"
  loop:
    - LCM_templates
    - component_templates
    - index_templates

- name: Copy LCM_templates to elasticsearch
  copy: src={{ item }} dest={{ es_conf_dir }}/templates/LCM_templates owner=root group=elasticsearch mode=0660
  register: load_templates
  with_fileglob:
    - "{{ es_LCM_templates_fileglob | default('')  }}"

#- name: test_send
#  debug: msg="{{ item | basename | regex_replace('^(.*)\\.[^\\.]*$','\\1') }}"
#  with_fileglob:
#    - "{{ es_LCM_templates_fileglob | default('') }}"


- name: Install LCM_templates
  uri:
    url: "{{ es_api_uri }}/_ilm/policy/{{ item | basename | regex_replace('^(.*)\\.[^\\.]*$','\\1') }}"
    method: PUT
    status_code: 200
    user:   "{{ es_api_basic_auth_username }}"
    password: "{{ es_api_basic_auth_password }}"
    force_basic_auth: yes
    body_format: json
    body: "{{ lookup('file', item) }}"
    validate_certs: "{{ es_validate_certs }}"
  when: load_templates.changed and es_start_service
  with_fileglob:
    - "{{ es_LCM_templates_fileglob | default('') }}"
  run_once: True
