---

- name: Setup elasticsearch users
  uri:
    url: "https://localhost:9200/_security/user/{{ item.username }}/_password"
    user: elastic
    password: "{{ es_api_basic_auth_password }}"
    method: POST
    body: {"password" : "{{ item.password }}"} 
    force_basic_auth: yes
    validate_certs: no
    status_code: 200
    body_format: json
  with_items: "{{ es_users }}"
  no_log: true
  run_once: true

- name: Setup extra elasticsearch roles
  uri:
    url: "https://localhost:9200/_security/role/{{ item.name }}"
    user: elastic
    password: "{{ es_api_basic_auth_password }}"
    method: POST
    body: {"cluster" : "{{ item.cluster }}", "indices": "{{ item.indices }}"}
    force_basic_auth: yes
    validate_certs: no
    status_code: 200
    body_format: json
  with_items: "{{ es_extra_roles }}"
  no_log: true
  run_once: true

- name: Setup extra elasticsearch users
  uri:
    url: "https://localhost:9200/_security/user/{{ item.username }}"
    user: elastic
    password: "{{ es_api_basic_auth_password }}"
    method: POST
    body: {"password" : "{{ item.password }}", "roles": "{{ item.roles }}"}
    force_basic_auth: yes
    validate_certs: no
    status_code: 200
    body_format: json
  with_items: "{{ es_extra_users }}"
  no_log: true
  run_once: true
