---

- name: CA exists
  stat:
    path:  "{{ es_certs_dir}}/{{ es_ca_filename }}"
  register: ca_file


- name: generate elasticsearch CA
  shell: 
    executable: "/bin/bash"
    cmd: "/usr/bin/openssl genrsa -out {{ es_certs_dir}}/{{ es_ca_filename }} 2048"
  when: not ca_file.stat.exists and not ansible_check_mode
  notify: Restart elasticsearch

- name: Copy CA to control node
  fetch:
    src:  "/etc/elasticsearch/certs/{{ es_ca_filename }}"
    dest: "{{ es_local_certs_dir }}/{{ es_ca_filename }}"
    flat: true
  when: not ca_file.stat.exists and not ansible_check_mode

- name: CA Attribute Change
  file:
    path: "{{ es_certs_dir}}/{{ es_ca_filename }}"
    state: file
    owner: "{{ es_user }}"
    group: "{{ es_group }}"
    mode: 0644
  when: not ca_file.stat.exists and not ansible_check_mode

- name: cert exists
  stat:
    path: "{{ es_certs_dir}}/{{ es_cert_filename }}"
  register: cert_file

- name: generate csr
  shell: 
    executable: "/bin/bash"
    cmd: /usr/bin/openssl req -new -key /etc/elasticsearch/certs/ca.key -subj "/C=JP/ST=Tokyo/L=Chiyoda-ku/O=NTT DOCOMO,INC" > /etc/elasticsearch/certs/ca.csr
  when: not cert_file.stat.exists and not ansible_check_mode

- name: Copy subjectnames file
  template:
    src: subjectnames_{{ release_env }}.j2
    dest: /tmp/subjectnames
    mode: 0400
  when: not cert_file.stat.exists and not ansible_check_mode

- name: generate cert
  shell: 
    executable: "/bin/bash"
    cmd: /usr/bin/openssl x509 -req -days {{ es_ca_effective_days }} -in {{ es_certs_dir}}/ca.csr -signkey {{ es_certs_dir}}/{{ es_ca_filename }} -out {{ es_certs_dir}}/{{ es_cert_filename }} -extfile /tmp/subjectnames
  when: not cert_file.stat.exists and not ansible_check_mode
  notify: Restart elasticsearch
  
- name: Copy cert to control node
  fetch:
    src:  "{{ es_certs_dir}}/{{ es_cert_filename }}"
    dest: "{{ es_local_certs_dir }}/{{ es_cert_filename }}"
    flat: true
  when: not cert_file.stat.exists and not ansible_check_mode

- name: Remove subjectnames file
  file:
    path: /tmp/subjectnames
    state: absent
