---
- name: Redmine コンテナホストディレクトリの作成
  ansible.builtin.file:
    path: "/opt/containers/{{ item }}"
    state: directory
    owner: "container_user"
    group: "container_user"
    mode: "0775"
  loop:
    - "redmine"
    - "redmine/config"
    - "redmine/mysql"

- name: Redmine コンテナの設定ファイルの配置(コピー)
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /opt/containers/redmine/
    mode: "0644"
    owner: "container_user"
    group: "container_user"
  loop:
    - files/storage.conf
    - files/subgid
    - files/subuid

- name: Redmine コンテナの設定ファイルの配置(テンプレート置換)
  ansible.builtin.template:
    src: templates/containers.conf.j2
    dest: /opt/containers/redmine/containers.conf
    owner: container_user
    group: container_user
    mode: "0644"

- name: Redmine コンテナイメージのビルド設定ファイルの配置(テンプレート置換)
  ansible.builtin.template:
    src: templates/redmine/Containerfile.j2
    dest: /opt/containers/redmine/Containerfile
    owner: container_user
    group: container_user
    mode: "0644"

- name: Redmine パッチ済み環境設定コードの配置(コンテナイメージビルド時にコンテナ内部にコピーする)
  ansible.builtin.copy:
    src: files/redmine/environment.rb
    dest: /opt/containers/redmine/config/environment.rb
    owner: container_user
    group: container_user
    mode: "0644"

- name: Redmine 設定ファイルの配置(テンプレート置換)
  ansible.builtin.template:
    src: templates/redmine/configuration.yml.j2
    dest: /opt/containers/redmine/config/configuration.yml
    owner: container_user
    group: container_user
    mode: "0644"

- name: Redmine DB設定ファイルの配置(テンプレート置換)
  ansible.builtin.template:
    src: templates/redmine/database.yml.j2
    dest: /opt/containers/redmine/config/database.yml
    owner: container_user
    group: container_user
    mode: "0644"

- name: MySQL コンテナイメージのビルド設定ファイルの配置(テンプレート置換)
  ansible.builtin.template:
    src: templates/mysql/Containerfile.j2
    dest: /opt/containers/redmine/mysql/Containerfile
    owner: container_user
    group: container_user
    mode: "0644"

- name: MySQL 設定ファイルの配置
  ansible.builtin.copy:
    src: files/mysql/my.cnf
    dest: /opt/containers/redmine/mysql/my.cnf
    owner: container_user
    group: container_user
    mode: "0644"

- name: Pod 定義ファイルの配置(テンプレート置換)
  ansible.builtin.template:
    src: templates/redminepod.yml.j2
    dest: /opt/containers/redmine/redminepod.yml
    owner: container_user
    group: container_user
    mode: "0644"
  register: redminepod_yml_result
