# SES Stack Configuration for Production (Primary EmailIdentity Owner)
template:
  type: file
  path: ses.yaml

dependencies:
  - prod/base.yaml

parameters:
  ProjectCode: ses-migration
  Environment: production
  DomainName: goo.ne.jp
  CloudWatchLogRetentionDays: 731
  S3BucketName: !stack_output prod/base.yaml::RawLogsBucketName
  SNSTopicArn: !stack_output prod/base.yaml::NotificationTopicArn

  # Required parameters
  AllowedIPRanges:
    - 202.217.0.0/16

  # SES IP Filtering Configuration (Production)
  SESAllowedIPs:
    - 202.217.75.98/32
    - 202.217.75.91/32
  EnableSESIPFiltering: "true"  # false Initially disabled for safety

  # SES Feature Configuration (Production as Primary)
  EnableBounceComplaintHandling: "true"
  EnableDKIM: "true"
  EnableDomainVerification: "true"
  EnableTokyoRegionFeatures: "true"
  EnableJapaneseCompliance: "true"
  EnableTokyoSES: "false"
  EnableJapaneseEmailTemplates: "true"

  # BYODKIM Configuration
  DKIMMode: "BYODKIM"
  BYODKIMSelector: "gooid-21-prod"
  BYODKIMPrivateKeyParameterName: "/ses-migration/prod/byodkim/private-key"
  BYODKIMForceRotation: "false"  # Change to "true" to force key rotation
  BYODKIMRotationInterval: 365
  EnableBYODKIMAutomation: "true"

  # Alert Thresholds (Production - stricter)
  BounceRateThreshold: 3.0
  ComplaintRateThreshold: 0.05
  SuccessRateThreshold: 98.0

  # Notification Settings
  NotificationEmail: ops@goo.ne.jp
  NotificationPhone: "+81901234567"

  # CloudWatch Settings
  CloudWatchMetricNamespace: "ses-migration/production/SES"

tags:
  Service: email
  Component: ses
  Environment: prod
  Project: ses-migration
  ManagedBy: sceptre
  Owner: infrastructure-team
  CostCenter: IT-001
  Production: true
  Critical: true
