# hlp
hlp_httpd_fqdn: gooid.wbo301.goo.ne.jp
hlp_httpd_port: 80
proxy_pass: gooid-21-dev-hlp-301:8081
hlp_proxysql:
  nodes:
    - gooid-21-dev-mdb-301
    - gooid-21-dev-mdb-302
    - gooid-21-dev-mdb-303
    - gooid-21-dev-sdb-301
    - gooid-21-dev-sdb-302
mysql_writer_host: 127.0.0.1:6034
mysql_reader_host: 127.0.0.1:6033
gbs_mule_host: gooid-21-dev-web-301:50080
