# msg
msg_httpd_fqdn: msg301.goo.ne.jp
msg_httpd_port: 80
msg_httpd_logformat: '"%h %l %u %t %D \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\""'
msg_httpd_logformat_type: "combined_gooidc"

# proxysql設定
msg_proxysql:
  # 最低でも1ノード、最大で5ノードまでを定義できます。
  # 
  # 1つ目のノードは、平常時の単一の書き込みノードになります。
  # 2～3つ目のノードは、
  #   （正常時）故障時に書き込みノードに昇格するために待機するノードです。参照もされません。
  #   （故障時）1つ目のノードが故障した際、単一書き込みノードに昇格します。
  # 4つ以上定義すると、4と5ノード目は、参照専用のノード（＝決して書き込みノードに昇格しない）となります。
  #
  # 詳細は、Jinja2テンプレート `roles/proxysql/templates/msg/proxysql.cnf.j2` を参照してください。
  nodes:
    - gooid-30-dev-mdb-301