# mdb

# galeraクラスタ設定
galera_cluster_name: IDHUB_GALERA_DB
galera_node_name: idhub_dev_db_5
galera_func: galera
galera_addr1: idhub-30-dev-sdb-102
galera_addr2: idhub-30-dev-mdb-102
galera_addr3: idhub-30-dev-mdb-103
galera_addr4: idhub-30-dev-sdb-101
galera_addr5: idhub-30-dev-mdb-101

