---
# 認証ファイルの配布
- name: Copy hospi-id-billing-pf.json
  copy:
    src: files/hospi-id-billing-pf-{{ release_env }}.json
    dest: /home/gooscp/hospi-id-billing-pf.json
    owner: gooscp
    group: gooscp
    mode: 0644

# 認証ファイルの読み込み
- name: gcloud auth activate-service-account
  shell: |
    gcloud config set proxy/type {{ proxy_env.fgw_proxy_type1 }}
    gcloud config set proxy/address {{ proxy_env.fgw_proxy_address }}
    gcloud config set proxy/port {{ proxy_env.fgw_proxy_port }}
    gcloud auth activate-service-account --key-file=/home/gooscp/hospi-id-billing-pf.json
  become: yes
  become_user: gooscp
