---

# ToDo: Ansible のdocker-compose プラグインを導入したら書き換える
- name: Compose up kibana 
  shell: |
      cd /opt/docker_container/kibana
      docker compose up -d
  register: up_result

- debug: { var: up_result.cmd.splitlines() } 

- debug: { var: up_result.stdout_lines }

- debug: { var: up_result.stderr_lines }
