---
- name: container-tools モジュール(4.0安定版)をインストール
  # Podman は container-tools モジュールに含まれている
  # タグ 4.0 を指定することで安定版をインストールする。
  # 将来的に Quadlet を使いたい場合は4.6以降に含まれているが、安定版タグは存在せず
  # 代わりに rhel8タグ (rolling stream、つまり最新版) を指定する必要がある。
  # ただし、最新版ストリームはバージョンが一定ではなく不安定になる可能性があるため
  # 今回は使わない。
  become: true
  block:
    - name: Check if container-tools stream is already enabled
      ansible.builtin.shell: |
        dnf module list container-tools | grep '\[e\]'
      register: container_tools_stream
      changed_when: false
      failed_when: false

    - name: Reset container-tools module stream if enabled
      ansible.builtin.command:
        cmd: dnf module reset -y container-tools
      when: container_tools_stream.rc == 0
      register: container_tools_reset
      changed_when: container_tools_reset.rc == 0

    - name: Enable container-tools:4.0 stream
      ansible.builtin.command:
        cmd: dnf module enable -y container-tools:4.0
      register: container_tools_enable
      changed_when: container_tools_enable.rc == 0

    - name: Install container-tools package group
      ansible.builtin.dnf:
        name: '@container-tools:4.0'
        state: present


# podman コマンドの代わりに docker コマンドも利用できるようにしておく
- name: install podman-docker 
  become: true
  ansible.builtin.dnf:
    name:   podman-docker
    state:  latest

# Install Docker/Podman Compose
#
# https://github.com/docker/compose/releases/download/v2.34.0/docker-compose-linux-x86_64
- name: Install Docker Compose
  become: true
  ansible.builtin.copy:
    src:  files/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: "0644"

- name: Install podman-compose
  ansible.builtin.pip:
    name: podman-compose==1.0.3
    executable: pip3
