---

- name: yum Upgrade all packages
  yum:
    name: '*'
    state: latest
  when: not ansible_check_mode

- name: Install Podman
  yum:
    name:   "{{ item }}"
    state:  present
  loop: 
    - podman 
    - podman-compose
  when: not ansible_check_mode



