---

- name: distribute containers.conf
  template:
    # src:        templates/containers.conf.j2
    src:        ../templates/containers.conf.j2
    dest:       /opt/containers/.config/containers/containers.conf
    owner:      container_user
    group:      container_user
    mode:       0644
  when: not ansible_check_mode

# docker コマンド実行時に警告が出ないようにする
- name: touch nodocker
  file: 
    path:   /etc/containers/nodocker
    state:  touch
    mode:   0644
    access_time: preserve
    modification_time: preserve
  when: not ansible_check_mode

- name: create user process directory
  file:
    path:     /run/user/1000
    state:    directory
    owner:    container_user
    group:    container_user
    mode:     0700

# rootless で起動させるための設定をユーザのUNITファイルとして配置する為のディレクトリ作成
- name: create configuration directory
  file:
    path:     /opt/containers/.config/systemd/user
    state:    directory
    owner:    container_user
    group:    container_user
    mode:     0744
    recurse:  yes

- name: deploy UNIT Files
  copy:
    src:  "{{ item }}"
    dest: /opt/containers/.config/systemd/user
    mode: 0644
  with_fileglob:
    - files/podman*

# systemctlによるルートレスPodmanのセットアップ
#sudo loginctl enable-linger container_user
- name:  enable linger
  command: loginctl enable-linger container_user

- name: enabled podman.socket
  systemd:
    name: podman.socket
    state: started 
    daemon_reload: yes
    scope: user
    enabled: yes
  become_user: container_user

- name: enable podman.service
  systemd:
    name: podman.service
    state: started 
    daemon_reload: yes
    scope: user
    enabled: yes
  become_user: container_user


