---
- name: Read allowed commands from control host file
  set_fact:
    allowed_commands: "{{ lookup('file', 'roles/rbash/files/allowed-commands-for-all.txt').splitlines() }}"

- name: Render motd using template
  template:
    src: "roles/bastion/templates/etc/motd.j2"
    dest: "/etc/motd"
    owner: root
    group: root
    mode: '0644'
  vars:
    allowed_commands: "{{ allowed_commands }}"
