AWSTemplateFormatVersion: '2010-09-09'
Description: 'SES Email Identity with BYODKIM - Complete Lambda Automation (Fixed Version)'

Parameters:
  ProjectCode:
    Type: String
    Default: 'ses-migration'
    Description: 'Project identifier for resource naming'
  Environment:
    Type: String
    Default: 'production'
    Description: 'Environment (production, staging, development)'
  DomainName:
    Type: String
    Default: 'goo.ne.jp'
    Description: 'Domain name for SES email identity'
  BYODKIMSelector:
    Type: String
    Default: 'gooid-21-prod'
    Description: 'BYODKIM selector for DNS TXT record'

Resources:
  # Lambda Execution Role
  BYODKIMAutomationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: BYODKIMAutomationPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ssm:PutParameter
                  - ssm:GetParameter
                  - ssm:DeleteParameter
                Resource:
                  - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/ses/byodkim/*'
              - Effect: Allow
                Action:
                  - ses:CreateEmailIdentity
                  - ses:DeleteEmailIdentity
                  - ses:PutEmailIdentityDkimSigningAttributes
                  - ses:PutEmailIdentityDkimAttributes
                  - ses:GetEmailIdentity
                  - ses:TagResource
                Resource: '*'

  # Lambda Layer for cryptography library
  CryptographyLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: !Sub '${ProjectCode}-cryptography-layer'
      Description: 'Cryptography library for RSA key generation'
      Content:
        S3Bucket: !Ref CryptographyLayerBucket
        S3Key: 'cryptography-layer.zip'
      CompatibleRuntimes:
        - python3.11
        - python3.12

  # S3 Bucket for Lambda Layer (temporary)
  CryptographyLayerBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectCode}-${Environment}-lambda-layers-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # Lambda Function for RSA Key Generation and SES Setup
  BYODKIMAutomationFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectCode}-${Environment}-byodkim-automation'
      Runtime: python3.11
      Handler: index.lambda_handler
      Role: !GetAtt BYODKIMAutomationRole.Arn
      Timeout: 300
      Environment:
        Variables:
          SSM_PRIVATE_KEY_PATH: '/ses/byodkim/private-key-base64'
          SSM_PUBLIC_KEY_PATH: '/ses/byodkim/public-key-dns'
      Code:
        ZipFile: |
          import json
          import boto3
          import base64
          import cfnresponse
          import subprocess
          import tempfile
          import os

          def lambda_handler(event, context):
              try:
                  print(f"Event: {json.dumps(event)}")

                  ssm = boto3.client('ssm')
                  ses = boto3.client('sesv2')

                  domain_name = event['ResourceProperties']['DomainName']
                  selector = event['ResourceProperties']['BYODKIMSelector']
                  project_code = event['ResourceProperties']['ProjectCode']
                  environment = event['ResourceProperties']['Environment']

                  if event['RequestType'] == 'Delete':
                      try:
                          # Delete SES identity
                          ses.delete_email_identity(EmailIdentity=domain_name)
                          print(f"Deleted SES identity: {domain_name}")
                      except Exception as e:
                          print(f"Error deleting SES identity: {e}")
                      try:
                          # Delete SSM parameters
                          ssm.delete_parameter(Name='/ses/byodkim/private-key-base64')
                          ssm.delete_parameter(Name='/ses/byodkim/public-key-dns')
                          print("Deleted SSM parameters")
                      except Exception as e:
                          print(f"Error deleting SSM parameters: {e}")
                      cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
                      return

                  if event['RequestType'] in ['Create', 'Update']:
                      # Try cryptography library first, fallback to OpenSSL
                      try:
                          from cryptography.hazmat.primitives import serialization
                          from cryptography.hazmat.primitives.asymmetric import rsa
                          from cryptography.hazmat.backends import default_backend

                          print("Using cryptography library for key generation")

                          # Generate RSA 2048-bit key pair
                          private_key = rsa.generate_private_key(
                              public_exponent=65537,
                              key_size=2048,
                              backend=default_backend()
                          )

                          # Serialize private key to PEM format
                          private_pem = private_key.private_bytes(
                              encoding=serialization.Encoding.PEM,
                              format=serialization.PrivateFormat.PKCS8,
                              encryption_algorithm=serialization.NoEncryption()
                          )

                          # Extract public key for DNS
                          public_key = private_key.public_key()
                          public_der = public_key.public_bytes(
                              encoding=serialization.Encoding.DER,
                              format=serialization.PublicFormat.SubjectPublicKeyInfo
                          )

                      except ImportError:
                          print("Cryptography library not available, using OpenSSL")

                          # Fallback: Use OpenSSL subprocess
                          with tempfile.TemporaryDirectory() as tmpdir:
                              private_key_path = os.path.join(tmpdir, 'private.pem')

                              # Generate private key using OpenSSL
                              subprocess.run([
                                  'openssl', 'genrsa', '-out', private_key_path, '2048'
                              ], check=True, capture_output=True)

                              # Read private key
                              with open(private_key_path, 'rb') as f:
                                  private_pem = f.read()

                              # Extract public key in DER format
                              result = subprocess.run([
                                  'openssl', 'rsa', '-in', private_key_path,
                                  '-pubout', '-outform', 'DER'
                              ], check=True, capture_output=True)
                              public_der = result.stdout

                      # Base64 encode keys
                      private_key_base64 = base64.b64encode(private_pem).decode('utf-8')
                      public_key_dns = base64.b64encode(public_der).decode('utf-8')

                      print(f"Generated keys - Private: {len(private_key_base64)} chars, Public: {len(public_key_dns)} chars")

                      # Store in SSM Parameter Store
                      ssm.put_parameter(
                          Name='/ses/byodkim/private-key-base64',
                          Value=private_key_base64,
                          Type='SecureString',
                          Description=f'BYODKIM private key for {domain_name} (base64 encoded)',
                          Overwrite=True
                      )

                      ssm.put_parameter(
                          Name='/ses/byodkim/public-key-dns',
                          Value=public_key_dns,
                          Type='String',
                          Description=f'BYODKIM public key for {domain_name} DNS TXT record',
                          Overwrite=True
                      )

                      print("Keys stored in SSM Parameter Store")

                      # Create SES Email Identity
                      try:
                          ses.create_email_identity(
                              EmailIdentity=domain_name,
                              Tags=[
                                  {'Key': 'Project', 'Value': project_code},
                                  {'Key': 'Environment', 'Value': environment},
                                  {'Key': 'DKIMType', 'Value': 'BYODKIM-Automated'},
                                  {'Key': 'CreatedBy', 'Value': 'Lambda-CloudFormation'}
                              ]
                          )
                          print(f"Created SES email identity: {domain_name}")
                      except ses.exceptions.AlreadyExistsException:
                          print(f"SES email identity already exists: {domain_name}")

                      # Configure BYODKIM
                      ses.put_email_identity_dkim_signing_attributes(
                          EmailIdentity=domain_name,
                          SigningAttributesOrigin='EXTERNAL',
                          SigningAttributes={
                              'DomainSigningSelector': selector,
                              'DomainSigningPrivateKey': private_key_base64
                          }
                      )

                      # Enable DKIM signing
                      ses.put_email_identity_dkim_attributes(
                          EmailIdentity=domain_name,
                          SigningEnabled=True
                      )

                      print(f"BYODKIM configured successfully for {domain_name}")

                      response_data = {
                          'EmailIdentity': domain_name,
                          'BYODKIMSelector': selector,
                          'DNSRecordName': f'{selector}._domainkey.{domain_name}',
                          'DNSRecordValue': f'v=DKIM1; k=rsa; p={public_key_dns}',
                          'PrivateKeySSMPath': '/ses/byodkim/private-key-base64',
                          'PublicKeySSMPath': '/ses/byodkim/public-key-dns',
                          'SetupStatus': 'Complete'
                      }

                      cfnresponse.send(event, context, cfnresponse.SUCCESS, response_data)

              except Exception as e:
                  print(f"Error: {str(e)}")
                  import traceback
                  traceback.print_exc()
                  cfnresponse.send(event, context, cfnresponse.FAILED, {'Error': str(e)})

  # Custom Resource for BYODKIM Automation
  BYODKIMAutomationResource:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !GetAtt BYODKIMAutomationFunction.Arn
      BYODKIMSelector: !Ref BYODKIMSelector
      DomainName: !Ref DomainName
      ProjectCode: !Ref ProjectCode
      Environment: !Ref Environment

  # SES Configuration Set
  SESConfigurationSet:
    Type: AWS::SES::ConfigurationSet
    Properties:
      Name: !Sub '${ProjectCode}-${Environment}-byodkim-config'
      Tags:
        - Key: Project
          Value: !Ref ProjectCode
        - Key: Environment
          Value: !Ref Environment
        - Key: CreatedBy
          Value: 'CloudFormation-Lambda'

Outputs:
  SESEmailIdentityName:
    Description: 'SES email identity name (created by Lambda)'
    Value: !GetAtt BYODKIMAutomationResource.EmailIdentity
    Export:
      Name: !Sub '${ProjectCode}-${Environment}-BYODKIM-Lambda-SESEmailIdentityName'

  BYODKIMSelector:
    Description: 'BYODKIM selector for DNS configuration'
    Value: !GetAtt BYODKIMAutomationResource.BYODKIMSelector
    Export:
      Name: !Sub '${ProjectCode}-${Environment}-BYODKIM-Lambda-Selector'

  BYODKIMDNSRecordName:
    Description: 'DNS TXT record name for BYODKIM public key'
    Value: !GetAtt BYODKIMAutomationResource.DNSRecordName
    Export:
      Name: !Sub '${ProjectCode}-${Environment}-BYODKIM-Lambda-DNSRecordName'

  BYODKIMDNSRecordValue:
    Description: 'DNS TXT record value for BYODKIM public key'
    Value: !GetAtt BYODKIMAutomationResource.DNSRecordValue
    Export:
      Name: !Sub '${ProjectCode}-${Environment}-BYODKIM-Lambda-DNSRecordValue'

  SESConfigurationSetName:
    Description: 'SES configuration set name'
    Value: !Ref SESConfigurationSet
    Export:
      Name: !Sub '${ProjectCode}-${Environment}-BYODKIM-Lambda-ConfigSet'

  PrivateKeyLocation:
    Description: 'SSM Parameter Store path for private key'
    Value: !GetAtt BYODKIMAutomationResource.PrivateKeySSMPath
    Export:
      Name: !Sub '${ProjectCode}-${Environment}-BYODKIM-Lambda-PrivateKeySSM'

  PublicKeyLocation:
    Description: 'SSM Parameter Store path for public key'
    Value: !GetAtt BYODKIMAutomationResource.PublicKeySSMPath
    Export:
      Name: !Sub '${ProjectCode}-${Environment}-BYODKIM-Lambda-PublicKeySSM'

  SetupStatus:
    Description: 'BYODKIM automation setup status'
    Value: !GetAtt BYODKIMAutomationResource.SetupStatus
    Export:
      Name: !Sub '${ProjectCode}-${Environment}-BYODKIM-Lambda-Status'
