AWSTemplateFormatVersion: '2010-09-09'
Description: 'SES Email Identity with Easy DKIM (2048-bit) - AWS Recommended Best Practice 2025'

Parameters:
  ProjectCode:
    Type: String
    Default: 'ses-migration'
    Description: 'Project identifier for resource naming'
  Environment:
    Type: String
    Default: 'production'
    Description: 'Environment (production, staging, development)'
  DomainName:
    Type: String
    Default: 'goo.ne.jp'
    Description: 'Domain name for SES email identity'

Resources:
  # SES Email Identity with Easy DKIM (2048-bit)
  SESEmailIdentityEasyDKIM:
    Type: AWS::SES::EmailIdentity
    Properties:
      EmailIdentity: !Ref DomainName
      DkimSigningAttributes:
        # Easy DKIM with 2048-bit key (AWS 2025 recommendation)
        NextSigningKeyLength: 'RSA_2048_BIT'
      DkimAttributes:
        SigningEnabled: true
      FeedbackAttributes:
        EmailForwardingEnabled: false
      Tags:
        - Key: Project
          Value: !Ref ProjectCode
        - Key: Environment
          Value: !Ref Environment
        - Key: DKIMType
          Value: 'EasyDKIM-2048bit'
        - Key: ManagedBy
          Value: 'CloudFormation'
        - Key: LastUpdated
          Value: '2025-09-05'

  # Configuration Set for Enhanced Monitoring
  SESConfigurationSet:
    Type: AWS::SES::ConfigurationSet
    Properties:
      Name: !Sub '${ProjectCode}-${Environment}-ses-config'
      Tags:
        - Key: Project
          Value: !Ref ProjectCode
        - Key: Environment
          Value: !Ref Environment

Outputs:
  SESEmailIdentityName:
    Description: 'SES email identity name'
    Value: !Ref SESEmailIdentityEasyDKIM
    Export:
      Name: !Sub '${ProjectCode}-${Environment}-EasyDKIM-SESEmailIdentityName'

  SESConfigurationSetName:
    Description: 'SES configuration set name'
    Value: !Ref SESConfigurationSet
    Export:
      Name: !Sub '${ProjectCode}-${Environment}-EasyDKIM-SESConfigurationSetName'

  DKIMType:
    Description: 'DKIM authentication type used'
    Value: 'Easy DKIM (2048-bit RSA)'
    Export:
      Name: !Sub '${ProjectCode}-${Environment}-EasyDKIM-Type'

  DNSInstructions:
    Description: 'Next steps for DNS configuration'
    Value: 'After stack creation, check SES Console for 3 CNAME records to add to DNS'
    Export:
      Name: !Sub '${ProjectCode}-${Environment}-EasyDKIM-DNSInstructions'

  DKIMTokenRetrievalCommand:
    Description: 'AWS CLI command to retrieve DKIM tokens for DNS setup'
    Value: !Sub 'aws sesv2 get-email-identity --email-identity ${DomainName} --query "DkimAttributes.Tokens" --output table'
    Export:
      Name: !Sub '${ProjectCode}-${Environment}-EasyDKIM-TokenCommand'
