---
- name: Create  directories
  file: path={{ item }} state=directory
  with_items:
  - /usr/local/app/script/

- name: Create  directories
  file: path={{ item }} state=directory owner=gooscp group=gooscp
  with_items:
  - /var/www/html/letsencrypt

- name: /etc/cron.d/update_ssl_rproxyの配置
  copy:
    src: files/etc/cron/update_ssl_{{server_kinds}}-{{release_env}}
    dest: /etc/cron.d/update_ssl
    backup: no 
    owner: root
    group: root
    mode: 0644
  when: inventory_hostname_short is regex("-rproxy-\d{3}$")

- name: /usr/local/app/script/update_letsencrypt_rproxy.shの配置
  copy:
    src: files/script/update_letsencrypt_rproxy.sh
    dest: /usr/local/app/script/update_letsencrypt_rproxy.sh
    backup: no 
    owner: root
    group: root
    mode: 0744
  when: inventory_hostname_short is regex("-rproxy-\d{3}$")

- name: /var/www/html/letsencrypt/host.htmlの配置
  template:
    src: templates/host.html.j2
    dest: /var/www/html/letsencrypt/host.html
    backup: no
    owner: gooscp
    group: gooscp
    mode: 0644
  when: inventory_hostname_short is regex("-rproxy-\d{3}$")

- name: Copy update_ssl_sudoers
  template:
    src: templates/update_ssl_sudoers.j2
    dest: /etc/sudoers.d/update_ssl_sudoers
    backup: yes 
    owner: root
    group: root
    mode: 0440
