# Production environment configuration
project_code: "aws-byodmim-prod"
region: "ap-northeast-1"

# Environment-specific settings
template_bucket_name: "aws-byodmim-prod-templates"
environment: "prod"
