# Phase 8: Monitoring System Start Phase
# Steps 26-28: Error logging, re-confirmation requests, scheduled monitoring setup

template_path: monitoring-system.yaml

parameters:
  ProjectName: !stack_output prod/phase-1-infrastructure-foundation.yaml::ProjectName
  Environment: !stack_output prod/phase-1-infrastructure-foundation.yaml::Environment
  DKIMManagerFunctionArn: !stack_output prod/phase-2-dkim-system.yaml::DKIMManagerFunctionArn
  DomainName: !stack_output prod/phase-1-infrastructure-foundation.yaml::DomainName
  MonitoringSchedule: "cron(0 0 1 * ? *)"  # 1st day of every month at 9:00 AM JST (0:00 UTC)
  CertificateValidityDays: 365  # Certificate validity period in days (1 year)
  RenewalAlertDays: 30  # Alert 30 days before expiration
  CriticalAlertDays: 7  # Critical alert 7 days before expiration
  WarningAlertDays: 30  # Warning alert 30 days before expiration

dependencies:
  - prod/phase-1-infrastructure-foundation.yaml
  - prod/phase-2-dkim-system.yaml
  - prod/phase-3-ses-byodkim.yaml
  - prod/phase-4-dns-preparation.yaml
  - prod/phase-5-dns-team-collaboration.yaml
  - prod/phase-7-dns-validation-dkim-activation.yaml

tags:
  Phase: "8-monitoring-system"
  Purpose: "Monitoring system start"
  Environment: prod
