template:
  type: file
  path: ../templates/enhanced-kinesis.yaml

dependencies:
  - prod/base.yaml

parameters:
  ProjectCode: aws-ses-migration
  Environment: production

  # Required parameters from Base stack
  RawLogsBucketName: !stack_output prod/base.yaml::RawLogsBucketName
  MaskedLogsBucketName: !stack_output prod/base.yaml::MaskedLogsBucketName
  ErrorLogsBucketName: !stack_output prod/base.yaml::ErrorLogsBucketName
  KMSKeyArn: !stack_output prod/base.yaml::KMSKeyArn
  LambdaRuntime: !stack_output prod/base.yaml::LambdaRuntime

  # Kinesis Configuration
  BufferSize: 128  # Production environment maximum value
  BufferInterval: 300
  CompressionFormat: GZIP
  RetentionDays: 2555  # Production environment long-term storage
  AdminIPRange: "10.0.0.0/8"
  OperatorIPRange: "192.168.100.0/24"

tags:
  Service: infrastructure
  Component: enhanced-kinesis
  Environment: prod
  Project: ses-migration
  ManagedBy: sceptre
  Owner: infrastructure-team
  CostCenter: IT-001
  Production: true
  Critical: true
  DataProcessing: true
