# Phase 3: SES Configuration and BYODKIM Initialization Phase
# Steps 11-13: SES Email Identity creation, BYODKIM setup, DKIM token generation

template_path: ses-configuration.yaml

parameters:
  ProjectName: !stack_output prod/phase-1-infrastructure-foundation.yaml::ProjectName
  Environment: !stack_output prod/phase-1-infrastructure-foundation.yaml::Environment
  DomainName: !stack_output prod/phase-1-infrastructure-foundation.yaml::DomainName
  DKIMManagerFunctionArn: !stack_output prod/phase-2-dkim-system.yaml::DKIMManagerFunctionArn
  DKIMSeparator: gooid-21-prod

dependencies:
  - prod/phase-1-infrastructure-foundation.yaml
  - prod/phase-2-dkim-system.yaml

tags:
  Phase: "3-ses-byodkim"
  Purpose: "SES configuration and BYODKIM initialization"
  Environment: prod
