# SES Sandbox Testing Configuration
# Purpose: Add verified email addresses for testing in sandbox mode
# Note: Required for testing before DNS delegation is complete

template:
  type: file
  path: ses-sandbox-testing.yaml

parameters:
  ProjectName: !stack_output prod/phase-1-infrastructure-foundation.yaml::ProjectName
  Environment: !stack_output prod/phase-1-infrastructure-foundation.yaml::Environment

  # Reference existing SES Configuration Set for consistent configuration
  SESConfigurationSetName: !stack_output prod/phase-3-ses-byodkim.yaml::ConfigurationSetName

  # Test email address for sandbox verification
  TestEmailAddress: "goo-idpay-sys@ml.nttdocomo.com"

dependencies:
  - prod/phase-1-infrastructure-foundation.yaml
  - prod/phase-3-ses-byodkim.yaml  # For ConfigurationSet reference

tags:
  Phase: "sandbox-testing"
  Purpose: "SES sandbox email verification for testing"
  Environment: prod
  TestingMode: "sandbox"
