# Clean Base Configuration for DEV
template:
  type: file
  path: ../templates/base.yaml

parameters:
  ProjectCode: ses-migration
  Environment: development
  RetentionDays: 90
  TransitionToIADays: 30
  TransitionToIntelligentTieringDays: 60
  TransitionToGlacierDays: 365
  TransitionToDeepArchiveDays: 365
  NotificationEmail: dev@goo.ne.jp

  # S3 Access Logging Configuration
  AccessLogDestinationBucket: service-logs-gooid-idhub

  # IP Restrictions (VDI/Ootemachi networks) - Same as prod for security
  AllowedSourceIPs:
    - "10.99.0.0/16"      # VDI/Ootemachi network
    - "10.88.80.0/20"     # VDI/Ootemachi network
    - "10.80.11.0/28"     # VDI/Ootemachi network
    - "10.80.0.0/24"      # VDI/Ootemachi network
    - "10.99.0.0/24"      # VDI/Ootemachi network
    - "202.217.0.0/16"    # SplashTop network

  # S3 Actions for Service Principals
  S3AllowedActions:
    - "s3:AbortMultipartUpload"
    - "s3:DeleteObject"
    - "s3:GetBucketLocation"
    - "s3:GetObject"
    - "s3:ListBucket"
    - "s3:ListBucketMultipartUploads"
    - "s3:ListMultipartUploadParts"
    - "s3:PutObject"

  # Service Principals for Raw Logs Bucket
  RawLogsServicePrincipals:
    - "firehose.amazonaws.com"
    - "delivery.logs.amazonaws.com"

  # Service Principals for Processing (Masked/Error Logs)
  ProcessingServicePrincipals:
    - "lambda.amazonaws.com"
    - "firehose.amazonaws.com"
