# Sceptre Dev Environment Configuration

# AWS Basic Configuration
region: ap-northeast-1
project_code: ses-migration
environment: dev

# Stack References
stacks:
  base: base.yaml
  ses: ses.yaml
  security: security.yaml
  monitoring: monitoring.yaml

# Common Tags
tags:
  Environment: dev
  Project: ses-migration
  ManagedBy: sceptre
  Owner: infrastructure-team
  CostCenter: IT-001
