# Security Stack Configuration
template:
  type: file
  path: ../templates/security.yaml

dependencies:
  - dev/base.yaml
  - dev/monitoring.yaml

parameters:
  ProjectCode: ses-migration
  Environment: development
  DomainName: goo.ne.jp

  # User Configuration
  AdminUsername: dev-admin
  ReadonlyUsername: dev-readonly
  MonitoringUsername: dev-monitoring
  AdminEmail: dev-admin@goo.ne.jp
  ReadonlyEmail: dev-readonly@goo.ne.jp
  MonitoringEmail: dev-monitoring@goo.ne.jp
  AdminPhone: "+81901234567"
  ReadonlyPhone: "+81901234568"
  MonitoringPhone: "+81901234569"

  # Required parameters
  AllowedIPRanges:
    - 10.0.0.0/8
    - 192.168.1.0/24

  # Feature Flags
  EnableIAMGroups: "true"
  EnableIAMUsers: "true"
  EnableIAMPolicies: "true"
  EnableAccessControl: "true"
  EnableIPRestriction: "false"
  EnablePersonalInformationProtection: "true"
  EnableJapaneseSecurity: "true"
  EnableJapaneseCompliance: "true"
  EnableTokyoRegionSecurity: "true"
  EnableTokyoRegionFeatures: "true"

  # CloudWatch Settings
  CloudWatchLogRetentionDays: 90

  # Output values from Monitoring stack
  DataMaskingFunctionArn: !stack_output dev/monitoring.yaml::DataMaskingFunctionArn
  AdminQueryDefinitionName: !stack_output dev/monitoring.yaml::AdminQueryDefinitionName
  MaskedQueryDefinitionName: !stack_output dev/monitoring.yaml::MaskedQueryDefinitionName

tags:
  Service: security
  Component: iam
  Environment: dev
  Project: ses-migration
  ManagedBy: sceptre
  Owner: infrastructure-team
  CostCenter: IT-001
