# SES Stack Configuration for Development (Depends on Production EmailIdentity)
template:
  type: file
  path: ../templates/ses-dev.yaml

dependencies:
  - dev/base.yaml
  - prod/ses.yaml  # Depends on Production SES for shared EmailIdentity

parameters:
  ProjectCode: ses-migration
  Environment: development
  DomainName: goo.ne.jp
  CloudWatchLogRetentionDays: 30
  S3BucketName: !stack_output dev/base.yaml::RawLogsBucketName
  SNSTopicArn: !stack_output dev/base.yaml::NotificationTopicArn

  # Required parameters
  AllowedIPRanges:
    - 202.217.0.0/16
    - 0.0.0.0/0

  # SES IP Filtering Configuration (Development)
  SESAllowedIPs:
    - 202.217.75.88/32
    - 202.217.75.81/32
  EnableSESIPFiltering: "true"

  # SES Feature Configuration (Development - simplified)
  EnableBounceComplaintHandling: "true"

  # Alert Thresholds (Development - more lenient)
  BounceRateThreshold: 10.0
  ComplaintRateThreshold: 0.5
  SuccessRateThreshold: 90.0

  # Notification Settings
  NotificationEmail: dev@goo.ne.jp
  NotificationPhone: "+81901234567"

  # CloudWatch Settings
  CloudWatchMetricNamespace: "ses-migration/development/SES"

tags:
  Service: email
  Component: ses
  Environment: dev
  Project: ses-migration
  ManagedBy: sceptre
  Owner: infrastructure-team
  CostCenter: IT-001
