---

#gooサービス用監視cron設定
- name: goo用監視cron設定の配布
  template:
    src: templates/monitor_goo.j2
    dest: /etc/cron.d/monitor_goo
    backup: yes
    owner: root
    group: root
    mode: 0644
  when: inventory_hostname_short is regex("^gooid-\d{2}")

#idhubサービス用監視cron設定
- name: idhub用監視cron設定の配布
  template:
    src: templates/monitor_idhub.j2
    dest: /etc/cron.d/monitor_idhub
    backup: yes
    owner: root
    group: root
    mode: 0644
  when: inventory_hostname_short is regex("^idhub-\d{2}")
