
- name: Create  directories
  file: path={{ item }} state=directory owner=gooscp group=gooscp mode=0755
  with_items:
  - /usr/local/app/monitoring

- name: Copy check_web_status.sh
  template:
    src: templates/check_web_status.sh.j2
    dest: /usr/local/app/monitoring/check_web_status.sh
    owner: gooscp
    group: gooscp
    mode: 0744
