---
- name: Jenkins サービス用ボリュームの準備
  become: true
  become_user: container_user
  block:
    - name: Jenkins データボリュームの作成
      containers.podman.podman_volume:
        name: jenkins_home
        driver: local
        state: present
    - name: Jenkins バックアップボリュームの作成
      containers.podman.podman_volume:
        name: jenkins_backup
        driver: local
        state: present

- name: データボリュームのマウントポイント(ローカルパス)を取得
  become: true
  become_user: container_user
  block:
    - name: ボリューム情報取得
      ansible.builtin.command: podman volume inspect jenkins_home
      register: volume_inspect_result
      changed_when: false
    - name: ボリューム情報から Mountpoint を抽出
      ansible.builtin.set_fact:
        mountpoint_jenkins_home: "{{ volume_inspect_result.stdout | from_json | json_query('[0].Mountpoint') }}"
      when: not ansible_check_mode
    - name: ディレクトリが確かに存在すること
      ansible.builtin.stat:
        path: "{{ mountpoint_jenkins_home }}"
      register: dir_info
      when: not ansible_check_mode
    - name: ボリュームのディレクトリが無ければエラー
      ansible.builtin.fail:
        msg: "The directory {{ mountpoint_jenkins_home }} does not exist."
      when: not ansible_check_mode and not dir_info.stat.exists

- name: バックアップボリュームのマウントポイント(ローカルパス)を取得
  become: true
  become_user: container_user
  block:
    - name: ボリューム情報取得
      ansible.builtin.command: podman volume inspect jenkins_backup
      register: volume_inspect_result
      changed_when: false
    - name: ボリューム情報から Mountpoint を抽出
      ansible.builtin.set_fact:
        mountpoint_jenkins_backup: "{{ volume_inspect_result.stdout | from_json | json_query('[0].Mountpoint') }}"
      when: not ansible_check_mode
    - name: ディレクトリが確かに存在すること
      ansible.builtin.stat:
        path: "{{ mountpoint_jenkins_backup }}"
      register: dir_info
      when: not ansible_check_mode
    - name: ボリュームのディレクトリが無ければエラー
      ansible.builtin.fail:
        msg: "The directory {{ mountpoint_jenkins_backup }} does not exist."
      when: not ansible_check_mode and not dir_info.stat.exists
