---
# containers.podman モジュールを使うには別途 containers.podman モジュールのインストールが必要
# インストールコマンド例：
# export HTTP_PROXY=http://172.17.255.232:8080
# export HTTPS_PROXY=http://172.17.255.232:8080
# ansible-galaxy collection install containers.podman

- name: Jenkins コンテナイメージのハッシュ値を取得
  become: true
  become_user: container_user
  block:
    - name: Jenkins イメージビルドの更新を検知するため現在のハッシュ値を取得
      containers.podman.podman_image_info:
        name: jenkins-podman:1.0.2
      register: prev_image_info
      ignore_errors: true
    - name: Hash値を取得
      ansible.builtin.set_fact:
        prev_image_hash: "{{ prev_image_info.images[0].Id if prev_image_info.images else '' }}"
    # - name: Debug image hash
    #  ansible.builtin.debug:
    #    msg: "Previous image hash: {{ prev_image_hash }}"

- name: Jenkins コンテナイメージのビルド
  become: true
  become_user: container_user
  block:
    - name: Build image
      ansible.builtin.command: podman build -t jenkins-podman:1.0.2 -f Containerfile /opt/containers/jenkins/
      changed_when: false
    - name: Image updated or not
      containers.podman.podman_image_info:
        name: jenkins-podman:1.0.2
      register: post_image_info
      changed_when: post_image_info.images[0].Id != prev_image_hash
    - name: Store whether iamge was updated
      ansible.builtin.set_fact:
        image_updated: "{{ post_image_info.images[0].Id != prev_image_hash }}"
