---
- name: Jenkins コンテナホストディレクトリの作成
  ansible.builtin.file:
    path: "/opt/containers/jenkins"
    state: directory
    owner: "container_user"
    group: "container_user"
    mode: "0775"

- name: Jenkins コンテナ設定ファイルの配置
  block:
    - name: 設定ファイルのコピー
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /opt/containers/jenkins/
        mode: "0644"
        owner: "container_user"
        group: "container_user"
      with_fileglob:
        - files/storage.conf
        - files/subgid
        - files/subuid

    - name: 設定ファイルの生成 - containers.conf
      ansible.builtin.template:
        src: templates/containers.conf.j2
        dest: /opt/containers/jenkins/containers.conf
        owner: container_user
        group: container_user
        mode: "0644"

    - name: コンテナイメージ Containerfile の生成
      ansible.builtin.template:
        src: templates/Containerfile.j2
        dest: /opt/containers/jenkins/Containerfile
        owner: container_user
        group: container_user
        mode: "0644"

    - name: Podman Compose ファイルの生成
      ansible.builtin.template:
        src: templates/podman-compose.yml.j2
        dest: /opt/containers/jenkins/podman-compose.yml
        owner: container_user
        group: container_user
        mode: "0644"
      when: not ansible_check_mode
