---
# Gitea pod を起動し、systemd サービスとして自動起動するよう登録する
#
- name: XDG_RUNTIME_DIR 設定値の取得(systemd関連コマンドに必要)
  # systemd --user を実行する際に環境変数 XDG_RUNTIME_DIR が参照される
  become: true
  become_user: container_user
  block:
    - name: Get UID of user
      ansible.builtin.command: id -u container_user
      register: user_uid_result
      changed_when: false
    - name: Set XDG_RUNTIME_DIR from UID
      ansible.builtin.set_fact:
        xdg_runtime_dir: "/run/user/{{ user_uid_result.stdout }}"

# Gitea Pod の再構築が必要かどうかを settings.yml, build.yml タスクの結果から判定する
# ※Pod構築ファイル(giteapod.yml)の変更、Gitea または DB イメージが更新された場合、
#   Gitea Pod の再起動(既存Podの削除と作成)が必要なため、
#   systemd ユニットファイルの再生成も必要となる。
- name: Gitea Pod の稼働状況の確認
  become: true
  become_user: container_user
  block:
    - name: Gitea pod が既に存在するかどうか調べる
      containers.podman.podman_pod_info:
        name: giteapod
      register: giteapod_info
      ignore_errors: true
    - name: Gitea pod が存在するかを giteapod_exists にセット
      ansible.builtin.set_fact:
        giteapod_exists: "{{ (giteapod_info.pods | default([])) | length > 0 }}"
    - name: Gitea pod の稼働状況を giteapod_running にセット
      ansible.builtin.set_fact:
        giteapod_running: >-
          {{
            (giteapod_info.pods | length > 0 and giteapod_info.pods[0].State == 'Running')
          }}
    - name: Gitea pod 状況チェックの結果
      ansible.builtin.debug:
        msg: >
          Pod 'giteapod' Status: Exits: {{ giteapod_exists }},
          Running: {{ giteapod_running }}

- name: Gitea Pod systemd サービスのユニット再起動が必要かどうか(pod_needs_restart)
  ansible.builtin.set_fact:
    pod_needs_restart: >-
      {{
        giteapod_yml_result.changed or
        gitea_image_updated or
        db_image_updated or
        not giteapod_running
      }}

- name: Gitea Pod systemd サービスの存在を確認(pod_service_exists)
  # ここでは systemd ユニットファイル名は 'pod-giteapod.service' と固定的に指定している。
  # これは podman_generate_systemd モジュールによるユニットファイル名生成ルールのデフォルト
  # に従っているため。
  become: true
  become_user: container_user
  block:
    - name: pod-giteapod.service ユニットファイルの確認
      ansible.builtin.stat:
        path: "/opt/containers/.config/systemd/user/pod-giteapod.service"
      register: unit_file_exists
      changed_when: false
    - name: 結果を pod_service_exists に
      ansible.builtin.set_fact:
        pod_service_exists: "{{ unit_file_exists.stat.exists }}"

- name: Gitea Pod systemd サービスの状況を確認(pod_service_activated)
  become: true
  become_user: container_user
  block:
    - name: pod-giteapod.service が Active かどうか
      ansible.builtin.command: systemctl --user is-active pod-giteapod.service
      register: pod_status_check
      changed_when: false
      failed_when: false
      environment:
        XDG_RUNTIME_DIR: "{{ xdg_runtime_dir }}"
    - name: 結果を pod_service_activated に
      ansible.builtin.set_fact:
        pod_service_activated: "{{ pod_status_check.stdout == 'active' }}"
    - name: サービスの稼働状況を出力(デバッグ用)
      ansible.builtin.debug:
        msg: >
          Gitea Pod Service is {{ 'ACTIVE' if pod_service_activated
            else 'NOT ACTIVE (status=' ~ pod_status_check.stdout ~ ')' }}

# ここまでの状況確認を元に Gitea Pod systemd サービスの再構築が必要かどうかを判定する
# 以下の状況に一つでも合致する場合にサービス再構築が必要
# ・コンテナイメージが更新(作成)された
# ・systemd ユニットファイルが未生成
- name: Gitea Pod systemd サービスの再構築が必要かどうか(service_needs_recreate)
  set_fact:
    service_needs_recreate: "{{ not pod_service_exists or pod_needs_restart }}"

- name: Gitea Pod systemd サービスの再構成と起動
  # systemd ユニットファイルは固定的なファイルがあるのではなく、
  # 都度作成したPod情報から生成する必要がある
  become: true
  become_user: container_user
  block:
    - name: Gitea Pod サービスの停止（アクティブだった場合）
      ansible.builtin.systemd_service:
        name: pod-giteapod
        state: stopped
        scope: user
        enabled: false
      environment:
        XDG_RUNTIME_DIR: "{{ xdg_runtime_dir }}"
      when: pod_service_activated
    - name: Gitea の app.ini を削除（必要な場合）
      # giteapod.yml 更新時は Gitea の app.ini を削除し、コンテナ起動時に再作成させる必要がある
      # mountpoint_gitea_data は build.yml 参照
      # app.ini のオーナーはコンテナ内ユーザー git であり、コンテナホストのユーザー container_user では
      # 削除できないため一時的に root になっている。
      become: true
      become_user: root
      ansible.builtin.file:
        path: "{{ mountpoint_gitea_data }}/_data/gitea/conf/app.ini"
        state: absent
      when: giteapod_yml_result.changed
    - name: Gitea Pod の起動(既にpodがあれば削除してから再作成する)
      # podman play kube コマンドは Pod を再起動する機能を持たないため、
      # 一度削除(DOWN)してから実行する必要があるが、 containers.podman.podman_play 
      # モジュールを使用することで簡易に記述できる（ recreate: true ）
      # Containers.Podman コレクションのバージョン 1.16.1 以降が必要
      containers.podman.podman_play:
        kube_file: /opt/containers/gitea/giteapod.yml
        recreate: true
        state: started
        debug: true
      environment:
        XDG_RUNTIME_DIR: "{{ xdg_runtime_dir }}"
    - name: Gitea Pod サービスの systemd ユニットファイルの生成
      become: true
      become_user: container_user
      containers.podman.podman_generate_systemd:
        name: giteapod
        dest: /opt/containers/.config/systemd/user
        force: true
        restart_policy: always
    - name: Redmime Pod サービスの起動
      # podman_generate_systemd でユニットファイルを生成した直後の systemd_service は相性が悪く、
      # 正常な起動を判断できないようだ。具体的には systemctl --user start 時にエラー
      # "Job for pod-giteapod.service failed because the service did not take the steps required by its unit configuration."
      # が報告され失敗したように見えるが、実際には正常に起動している。
      # 実際に起動したかどうかはこの後のタスクで保証する
      ansible.builtin.systemd_service:
        name: pod-giteapod
        scope: user
        daemon_reload: true
        state: started
        enabled: true
      environment:
        XDG_RUNTIME_DIR: "{{ xdg_runtime_dir }}"
      ignore_errors: true
  when: service_needs_recreate 

- name: Gitea Pod サービス起動を保証する
  become: true
  become_user: container_user
  ansible.builtin.systemd_service:
    name: pod-giteapod.service
    scope: user
    state: started
    enabled: true
  environment:
    XDG_RUNTIME_DIR: "{{ xdg_runtime_dir }}"
