---
- name: Gitea コンテナホストディレクトリの作成
  ansible.builtin.file:
    path: "/opt/containers/gitea"
    state: directory
    owner: "container_user"
    group: "container_user"
    mode: "0775"

- name: Gitea コンテナの設定ファイルの配置(コピー)
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /opt/containers/gitea/
    mode: "0644"
    owner: "container_user"
    group: "container_user"
  loop:
    - files/storage.conf
    - files/subgid
    - files/subuid

- name: Gitea コンテナの設定ファイルの配置(テンプレート置換)
  ansible.builtin.template:
    src: templates/containers.conf.j2
    dest: /opt/containers/gitea/containers.conf
    owner: container_user
    group: container_user
    mode: "0644"

- name: Gitea コンテナイメージのビルド設定ファイルの配置(テンプレート置換)
  ansible.builtin.template:
    src: templates/gitea/Containerfile.j2
    dest: /opt/containers/gitea/Containerfile
    owner: container_user
    group: container_user
    mode: "0644"

- name: MySQL コンテナ設定ディレクトリの作成
  ansible.builtin.file:
    path: "/opt/containers/gitea/mysql"
    state: directory
    owner: "container_user"
    group: "container_user"
    mode: "0755"

- name: MySQL コンテナイメージのビルド設定ファイルの配置(テンプレート置換)
  ansible.builtin.template:
    src: templates/mysql/Containerfile.j2
    dest: /opt/containers/gitea/mysql/Containerfile
    owner: container_user
    group: container_user
    mode: "0644"

- name: MySQL 設定ファイルの配置
  ansible.builtin.copy:
    src: files/mysql/my.cnf
    dest: /opt/containers/gitea/mysql/my.cnf
    owner: container_user
    group: container_user
    mode: "0644"

- name: Pod 定義ファイルの配置(テンプレート置換)
  ansible.builtin.template:
    src: templates/giteapod.yml.j2
    dest: /opt/containers/gitea/giteapod.yml
    owner: container_user
    group: container_user
    mode: "0644"
  register: giteapod_yml_result
