---
# 検証環境のパッケージのインストール
- yum:
    name: "{{ packages }}"
    state: installed
    enablerepo: private
    disablerepo: "*"
  when: release_env == "dev"
  vars:
    packages:
      - java-{{ jdk_version }}-openjdk
      - java-{{ jdk_version }}-openjdk-devel

# 商用環境のパッケージのインストール
- yum:
    name: "{{ packages }}"
    state: installed
    enablerepo: private
    disablerepo: "*"
  when: release_env == "pro"
  environment: "{{ proxy_env }}"
  vars:
    packages:
      - java-{{ jdk_version }}-openjdk
      - java-{{ jdk_version }}-openjdk-devel
