---

# 現在mariadb のインストールにはprivate リポジトリを使用しているのでPlaybookを一旦分けている
# 将来的にはinstall.yml にマージする
- name: distribute mariadb repo
  template:
    src:        templates/etc/yum.repos.d/mariadb.repo.j2
    dest:       /etc/yum.repos.d/mariadb.repo
    owner:      root
    group:      root
    mode:       0644

- name: install Mariabackup
  yum:
    name: 
      - MariaDB-backup
    state: latest
  when: not ansible_check_mode

# private リポジトリの問題が解決するまではMariabackupインストールが済み次第こちらは削除しておく
- name: delete mariadb repo
  file:
    path: /etc/yum.repos.d/mariadb.repo
    state: absent
