
###
### rootパスワードやアクセス権の設定
### Playbook は root権限を持つ、 idc_alladmin が予め存在する前提で、
### 以降、この特権ユーザを利用して各種ユーザが作られる仕組み。
###
###

- name: rootユーザが登録されているか確認
  # ログにPasswordなどが残らないようにする。
  #no_log: true
  block:
    - mysql_info:
        login_host: localhost
        login_user: "{{ mysql_admin_name }}"
        login_password: "{{ mysql_admin_password }}"
  rescue:
    - import_tasks: set_root.yml

- name: Create MySQL user and set password
  # ログにPasswordなどが残らないようにする。
  #no_log: true
  mysql_user:
    login_user: "{{ mysql_admin_name }}"
    login_password: "{{ mysql_admin_password }}"
    name: "{{ item.0.name }}"
    password: "{{ item.0.password }}"
    priv: "{{ item.0.priv }}"
    host: "{{ item.1 }}"
  with_subelements:
    - "{{ mysql.users }}"   # vault.ymlの変数を直接アクセス
    - hosts
  when: galera_cluster_leader is defined
