---
- name: mariadb.serviceの設定
  systemd:
    name: mariadb.service
    enabled: no
    daemon_reload: no

- name: mariadb.serviceの開発環境自動起動設定
  systemd:
    name: mariadb.service
    state: started
    enabled: yes
    daemon_reload: no
  when: release_env == "dev"
