FROM docker.io/gitea/gitea:1.24.3

USER root

ENV http_proxy="{{ proxy_env.http_proxy }}"
ENV https_proxy="{{ proxy_env.http_proxy }}"
ENV HTTP_PROXY="{{ proxy_env.http_proxy }}"
ENV HTTPS_PROXY="{{ proxy_env.http_proxy }}"
ENV no_proxy="localhost,127.0.0.1"
ENV NO_PROXY="localhost,127.0.0.1"
ENV TZ=Asia/Tokyo

# タイムゾーンを Asia/Tokyo に設定
RUN apk add --no-cache tzdata \
    && cp /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo "$TZ" > /etc/timezone \
    && apk del tzdata

# EOS
