# Production environment configuration
project_code: "aws-ses-migration-prod"
region: "ap-northeast-1"

# Environment-specific settings
template_bucket_name: "aws-ses-migration-prod-templates"
environment: "prod"
