# Phase 2: DKIM Management System Construction Phase
# Steps 7-10: DKIM Manager Lambda, Lambda execution role, KMS access, Secrets access

template_path: dkim-manager-lambda.yaml

parameters:
  ProjectName: !stack_output prod/phase-1-infrastructure-foundation.yaml::ProjectName
  Environment: !stack_output prod/phase-1-infrastructure-foundation.yaml::Environment
  DKIMManagerRoleArn: !stack_output prod/phase-1-infrastructure-foundation.yaml::DKIMManagerRoleArn
  DKIMConfigSecretArn: !stack_output prod/phase-1-infrastructure-foundation.yaml::DKIMConfigSecretArn
  DKIMCertificatesBucketName: !stack_output prod/phase-1-infrastructure-foundation.yaml::DKIMCertificatesBucketName
  DKIMEncryptionKeyArn: !stack_output prod/phase-1-infrastructure-foundation.yaml::DKIMEncryptionKeyArn
  # CryptographyLayerArn removed - Layer will be created automatically by CloudFormation
  CryptographyLayerKey: cryptography-layer.zip  # Layer ファイルのS3キー
  CertificateValidityDays: 2    # 2 days validity for testing
  RenewalAlertDays: 1           # Alert 1 day before expiration

dependencies:
  - prod/phase-1-infrastructure-foundation.yaml

tags:
  Phase: "2-dkim-system"
  Purpose: "DKIM management system"
  Environment: prod
