# Security Stack Configuration for Production
template:
  type: file
  path: security.yaml

dependencies:
  - prod/base.yaml
  - prod/monitoring.yaml

parameters:
  ProjectCode: aws-ses-migration
  Environment: production
  DomainName: goo.ne.jp

  # User Configuration
  AdminUsername: prod-admin
  ReadonlyUsername: prod-readonly
  MonitoringUsername: prod-monitoring
  AdminEmail: admin@goo.ne.jp
  ReadonlyEmail: readonly@goo.ne.jp
  MonitoringEmail: monitoring@goo.ne.jp
  AdminPhone: "+81901234567"
  ReadonlyPhone: "+81901234568"
  MonitoringPhone: "+81901234569"

  # Required parameters
  AllowedIPRanges:
    - 10.0.0.0/8
    - 192.168.100.0/24

  # Feature Flags (Production - more secure)
  EnableIAMGroups: "true"
  EnableIAMUsers: "true"
  EnableIAMPolicies: "true"
  EnableAccessControl: "true"
  EnableIPRestriction: "true"
  EnablePersonalInformationProtection: "true"
  EnableJapaneseSecurity: "true"
  EnableJapaneseCompliance: "true"
  EnableTokyoRegionSecurity: "true"
  EnableTokyoRegionFeatures: "true"

  # CloudWatch Settings
  CloudWatchLogRetentionDays: 731

  # Output values from Monitoring stack
  DataMaskingFunctionArn: !stack_output prod/monitoring.yaml::DataMaskingFunctionArn
  AdminQueryDefinitionName: !stack_output prod/monitoring.yaml::AdminQueryDefinitionName
  MaskedQueryDefinitionName: !stack_output prod/monitoring.yaml::MaskedQueryDefinitionName

tags:
  Service: security
  Component: iam
  Environment: prod
  Project: ses-migration
  ManagedBy: sceptre
  Owner: infrastructure-team
  CostCenter: IT-001
  Production: true
  Critical: true
