---
- name: log削除用configの配布先ディレクトリの作成
  file: path={{ item }} state=directory owner=idclog group=idclog mode=0700
  with_items:
  - /home/idclog

- name: log削除用configの配布先ディレクトリの作成
  file: path={{ item }} state=directory owner=idclog group=idclog mode=0755
  with_items:
  - /home/idclog/gathering_log

- name: log収集用cronの配布
  copy:
    src: files/cron/log_Harvester
    dest: /etc/cron.d/log_Harvester
    owner: root
    group: root
    mode: 0644

- name: log収集用scriptの配布
  copy:
    src: files/script/log_Harvester.sh
    dest: /home/idclog/log_Harvester.sh
    owner: idclog
    group: idclog
    mode: 0744

- name: log収集用configの配布
  template:
    src: templates/config/gathering_log/{{ item ~ ".j2" }}
    dest: /home/idclog/gathering_log/{{ item }}
    owner: idclog
    group: idclog
    mode: 0644
  loop:
    - logharvest_gooid_web00x
    - logharvest_gooid_batch00x
    - logharvest_gooid_fgw00x
    - logharvest_gooid_hlp00x
    - logharvest_gooid_log00x
    - logharvest_gooid_mdb00x
    - logharvest_gooid_msg00x
    - logharvest_gooid_oidc00x
    - logharvest_gooid_sdb00x
    - logharvest_gooid_edb00x
    - logharvest_gooid_rproxy00x
    - logharvest_gooid_host00x
    - logharvest_idhub_batch00x
    - logharvest_idhub_hlp00x
    - logharvest_idhub_mdb00x
    - logharvest_idhub_sdb00x
    - logharvest_idhub_web00x
    - logharvest_idhub_rproxy00x
