---
- name: create /db0 directory
  file:
    path: "/db0"
    state: directory
    owner: "root"
    group: "root"
    mode: "755"

# /db0/app
- name: idhub batch に必要な /db0/app/goo 配下のディレクトリを作成します。
  file:
    path: "{{ item.path }}"
    state: directory
    owner: gooscp
    group: gooscp
    mode: "{{ item.mode }}"
  loop:
  # 2024-11-13 利用していないDIRを精査し、本当に必要なDIRのみ列挙した。
  #
  # 確認した方法は以下の通り。
  # $ find /db0/app/ -type f -mtime -365 | perl -pe 's|\/[^\/]+$|\n|g' | sort -u
  #    - 1年以内に更新された「あったかい」ファイルを保持しているディレクトリのみを列挙
  #
    - { path: /db0/app, mode: '0755' }
    - { path: /db0/app/goo, mode: '0755' }
    - { path: /db0/app/goo/batch_file, mode: '0777' }
    - { path: /db0/app/goo/batch_file/COMMON, mode: '0755'}
    - { path: /db0/app/goo/batch_file/COMMON/hospitality, mode: '0755'}
    - { path: /db0/app/goo/batch_file/COMMON/hospitality/v2, mode: '0755'}
    - { path: /db0/app/goo/batch_file/idhub, mode: '0755'}
    - { path: /db0/app/goo/batch_file/idhub/common, mode: '0755'}
    - { path: /db0/app/goo/batch_file/idhub/point, mode: '0755'}
    - { path: /db0/app/goo/batch_file/idhub/report, mode: '0755'}
