AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 bucket for Lambda function code'

Parameters:
  ProjectName:
    Type: String
    Default: poc
    Description: Name of the project

Resources:
  LambdaCodeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${ProjectName}-lambda-code-${AWS::AccountId}
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

Outputs:
  BucketName:
    Description: Name of the S3 bucket for Lambda code
    Value: !Ref LambdaCodeBucket
    Export:
      Name: !Sub ${ProjectName}-lambda-code-bucket
