---
# {{ item ~ ".j2" }}で2つの文字列を連結
- name: /etc/httpd/conf配下の設定ファイルを配布
  template:
    src: templates/gooid/conf/{{ item }}-{{ release_env }}.j2
    dest: /etc/httpd/conf/{{ item }}
    owner: root
    group: root
    mode: 0644
  loop:
    - acl-servers.conf
    - httpd.conf
    - acl-no-otp-servers.conf
  notify:
    - httpd_rproxy_restart_msg
  when: release_env == "pro"

# {{ item ~ ".j2" }}で2つの文字列を連結
- name: /etc/httpd/conf配下の設定ファイルを配布
  template:
    src: templates/gooid/conf/{{ item }}-{{ release_env }}.j2
    dest: /etc/httpd/conf/{{ item }}
    owner: root
    group: root
    mode: 0644
  loop:
    - acl-servers.conf
    - httpd.conf
  notify:
    - httpd_rproxy_restart_msg
  when: release_env == "dev"

# {{ item ~ ".j2" }}で2つの文字列を連結
- name: /etc/httpd/conf.d配下の設定ファイルを配布
  template:
    src: templates/gooid/conf.d/{{ item }}-{{release_env}}.j2
    dest: /etc/httpd/conf.d/{{ item }}
    owner: root
    group: root
    mode: 0644
  loop:
    - 1.login.mail.goo.ne.jp.conf
    - 2.auth.d.goo.ne.jp.conf
    - builder.gooid.wbo110.goo.ne.jp.conf
    - fgw120.goo.ne.jp.conf
    - gooid.wbo110.goo.ne.jp.conf
    - http.conf
    - srvc.goo.ne.jp.conf
    - ssl.conf
    - wbo110.goo.ne.jp.conf
    - auth.goo.ne.jp.conf
    - graph.wbo110.goo.ne.jp.conf
  notify:
    - httpd_rproxy_restart_msg
  when: release_env == "pro"

# {{ item ~ ".j2" }}2でつの文字列を連結
- name: /etc/httpd/conf.modules.d配下の設定ファイルを配布
  template:
    src: templates/gooid/conf.modules.d/{{ item }}-{{ release_env }}.j2
    dest: /etc/httpd/conf.modules.d/{{ item }}
    owner: root
    group: root
    mode: 0644
  loop:
    - 00-base.conf
    - 00-lua.conf
    - 00-mpm.conf
    - 00-proxy.conf
    - 00-ssl.conf
    - 00-systemd.conf
    - 01-cgi.conf
  notify:
    - httpd_rproxy_restart_msg
  when: release_env == "pro"

# {{ item ~ ".j2" }}2でつの文字列を連結
- name: /etc/httpd/conf.modules.d配下の設定ファイルを配布
  template:
    src: templates/gooid/conf.modules.d/{{ item }}-{{ release_env }}.j2
    dest: /etc/httpd/conf.modules.d/{{ item }}
    owner: root
    group: root
    mode: 0644
  loop:
    - 00-base.conf
    - 00-lua.conf
    - 00-mpm.conf
    - 00-proxy.conf
    - 00-ssl.conf
    - 00-systemd.conf
    - 01-cgi.conf
    - 01-ldap.conf
  notify:
    - httpd_rproxy_restart_msg
  when: release_env == "dev"


- name: /etc/httpd/conf.d配下の設定ファイルを配布
  template:
    src: templates/gooid/conf.d/virtualhost.conf-{{ release_env }}.j2
    dest: /etc/httpd/conf.d/{{ item.0.servername }}.conf
    owner: root
    group: root
    mode: 0644
  with_subelements:
    - "{{ rproxy.httpd_conf }}"   # rproxy.ymlの変数を直接アクセス
    - proxy
  notify:
    - httpd_rproxy_restart_msg
  when: release_env == "dev"

# SSL証明書配置用ディレクトリを作成する
- name: Make directory
  file: path={{ item }} state=directory owner=tomcat group=tomcat
  with_items:
  - /etc/httpd/ssl

# SSL証明書を配布する
# 本証明書はIP直接指定でアクセスされた際に
# アクセスを拒否するためのdefalt:443ディレクティブ用の証明書である
- name: /etc/httpd/conf.modules.d配下の設定ファイルを配布
  copy:
    src: files/ssl/{{ item }}
    dest: /etc/httpd/ssl/{{ item }}
    owner: root
    group: root
    mode: 0644
  loop:
    - default.crt
    - default.key
  notify:
    - httpd_rproxy_restart_msg

- name: フォルダ(/etc/httpd/otp)を作成する
  file:
    path: /etc/httpd/otp
    state: directory
    owner: apache
    group: apache
    mode: 0755
    recurse: true

# OTP認証用の設定ファイルを配布する
- name: /etc/httpd/otp配下の設定ファイルを配布
  copy:
    src: files/otp/{{ item }}
    dest: /etc/httpd/otp/{{ item }}
    owner: apache
    group: apache
    mode: 0600
  loop:
    - users.pin
    - users.token
  tags: otp

- name: add_otpuser.sh ユーティリティを配布
  copy:
    src: files/otp/add_otpuser.sh
    dest: /etc/httpd/otp/add_otpuser.sh
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"
  tags: otp

- name: README.md配置
  copy:
    src: files/otp/README.md
    dest: /etc/httpd/otp/README.md
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  tags: otp
