---

project_id_number_env: "30-dev"

# Elasticsearch 再作成に伴い依存関係にあるものは一時コメントアウト
td_agent_config_files:
  - file_dir: "common"
    file_name:
      - "os_logs"
  - file_dir: "gooid-web"
    file_name:
      - "gbs"
      - "httpd_access_log"
      - "httpd_error_log"
      - "httpd_gbs_access_log"
      - "httpd_gbs_error_log"
      - "httpd_modsec_audit"
      - "httpd_modsec_performance"
      - "idc"
      - "proxysql"
      - "tomcat_idc"
  - file_dir: "zabbix-sender"
    file_name:
      - "httpd_access_count"
      - "app_idc_user_count"
      - "app_idc_openid_count"
      - "app_gbss_event_spring_count"
      - "app_gbss_error_spring_count"
      - "app_gbss_debug_spring_count"
      - "app_idhub-oidc_audit_count"
      - "app_idhub-oidc_request_count"
      - "app_idhub_user_count"
      - "app_idc_helptoolwebapp_count"
      - "app_idc_show_report_count"
      - "app_gbs_gbs_webapps_count"
      # - "app_gbs_gbs_mule_count"
      - "app_idhub_helptoolwebapp_count"
      - "app_gbs_scp_gbs_batch_count"
      # - "CheckShopifyCustomerRegistrationStatus_count"
      - "cluster_corosync_count"
      # - "make_common_reject_list_count"
      # - "oshiete_member_count"
      # - "update_ip2country_count"
      # - "DeleteAuthenticationSession_count"
      # - "make_active_gooid_list_count"
      # - "make_denied_privacy_list_count"
      # - "make_hospitality_list_count"
      # - "DeleteRegisterSession_count"
      # - "DeleteReSettingPasswordInfo_count"
      # - "DeleteAuthTelephoneHistory_count"
      # - "ExportLoginHistory_count"
      # - "DeleteAccessRiskHistory_count"
      # - "ServiceReport_count"
      # - "make_reject_account_list_count"
      # - "delete_temporary_register_account_count"
      # - "delete_authn_session_count"
      # - "delete_expired_history_count"
      # - "make_active_account_list_count"
      # - "make_goo_active_account_list_count"
      # - "make_register_error_account_list_count"
      # - "make_add_uid_error_account_list_count"
      # - "make_ocn_disconnect_error_account_list_count"
      # - "make_ocn_dpointcard_error_account_list_count"
      # - "make_goo_register_error_account_list_count"
      # - "make_goo_disconnect_error_account_list_count"
      # - "make_goo_dpointcard_error_account_list_count"
      # - "make_goo_active_account_monthly_list_count"
      # - "make_docomo_link_info_list_count"
      # - "delete_personal_data_count"
      - "oidc_audit_count"
      - "oidc_request_count"
      - "httpd_idhub_access_count"
      - "alert_test_user_count"
      - "idc_counts"
      - "oidc_audit_and_request_counts"
  - file_dir: "idhub-web"
    file_name:
      - "idhub-oidc"
      - "user"
      - "httpd_access_log"
      - "httpd_error_log"
      - "proxysql"
  - file_dir: "gooid-hlp"
    file_name:
      - "helptoolwebapp"
      - "show_report"
      - "gbs_webapps"
      - "gbs_mule"
      - "httpd_access_log"
      - "httpd_ssl_access_log"
      - "ProfileToolOpe"
      - "ProfileToolAuth"
  - file_dir: "idhub-hlp"
    file_name:
      - "helptoolwebapp"
      - "httpd_access_log"
      - "httpd_ssl_access_log"
      - "ProfileToolOpe"
      - "ProfileToolAuth"
  - file_dir: "gooid-batch"
    file_name:
      - "make_common_reject_list"
      - "oshiete_member"
      - "update_ip2country"
      - "DeleteAuthenticationSession"
      - "make_active_gooid_list"
      - "make_denied_privacy_list"
      - "make_hospitality_list"
      - "DeleteRegisterSession"
      - "DeleteReSettingPasswordInfo"
      - "DeleteAuthTelephoneHistory"
      - "ExportLoginHistory"
      - "DeleteAccessRiskHistory"
      - "ServiceReport"
      - "CheckShopifyCustomerRegistrationStatus"
      - "gbs_batch"
      - "corosync"
  - file_dir: "idhub-batch"
    file_name:
      - "make_reject_account_list"
      - "delete_temporary_register_account"
      - "delete_authn_session"
      - "delete_expired_history"
      - "make_active_account_list"
      - "make_goo_active_account_list"
      - "make_register_error_account_list"
      - "make_add_uid_error_account_list"
      - "make_ocn_disconnect_error_account_list"
      - "make_ocn_dpointcard_error_account_list"
      - "make_goo_register_error_account_list"
      - "make_goo_disconnect_error_account_list"
      - "make_goo_dpointcard_error_account_list"
      - "make_goo_active_account_monthly_list"
      - "make_docomo_link_info_list"
      - "delete_personal_data"
  # - file_dir: "td-agent"
    # file_name:
      # - "td-agent_log"
  - file_dir: "gooid-oidc"
    file_name:
      - "oidc_audit"
      - "oidc_request"
      - "httpd_error_log"
      - "httpd_access_log"
  # - file_dir: "test"
    # file_name:
      # - "alert_test_access_log"
      # - "alert_test_access_log_tail"
  - file_dir: "elastic-sender"
    file_name:
      - "messages"
      - "secure"
      - "yum"
      - "httpd_error_log"
      - "modsec_audit"
      - "modsec_performance"
      - "gbs_access_log"
      - "gbs_error_log"
      - "proxysql"
      - "idhub_httpd_error_log"
      - "idhub_proxysql"
      - "gooid_hlp_app_idc_ProfileToolAuth"
      - "gooid_hlp_app_idc_ProfileToolOpe"
      - "gooid_hlp_httpd_access_log"
      - "gooid_hlp_httpd_ssl_access_log"
      - "gooid_oidc_httpd_access_log"
      - "gooid_oidc_httpd_error_log"
      - "idhub_hlp_app_idhub_ProfileToolAuth"
      - "idhub_hlp_app_idhub_ProfileToolOpe"
      - "idhub_hlp_httpd_access_log"
      - "idhub_hlp_httpd_ssl_access_log"


# Elasticsearchパスワード 
elasticsearch:
  hostname:     "idhub-30-dev-els-002" #下記hosts で転送先のラウンドロビンに問題なければ使用しない
  hosts:        "idhub-30-dev-els-002:9200,idhub-30-dev-els-003:9200"
  user:         "elastic"
  pwd:          "{{ vault_elasticsearch_password }}"
  ssl_version:  "TLSv1_2"
  ca_file:      "/etc/td-agent/certs/ca/http_ca.crt"

# td-agentワーカー数
td_agent_workers:	4

# td-agent各ワーカー名
td_agent_worker0:	0
td_agent_worker1:	1
td_agent_worker2:	0
td_agent_worker3:	2

zabbix_servers:
  - server: 172.17.32.101
    port:   6951
  # - server: 172.17.32.102
    # port:   6951

fgw_servers:
  - server: gooid-21-dev-fgw-101
    ip: 172.25.75.64
  # - server: gooid-30-dev-fgw-602 # テスト時のみ追記
    # ip: 172.17.102.28

sysctl_settings:
  - name: net.core.somaxconn
    value: 1024
  - name: net.core.netdev_max_backlog
    value: 5000
  - name: net.core.rmem_max
    value: 16777216
  - name: net.core.wmem_max
    value: 16777216
  - name: net.ipv4.tcp_wmem
    value: 4096 12582912 16777216
  - name: net.ipv4.tcp_rmem
    value: 4096 12582912 16777216
  - name: net.ipv4.tcp_max_syn_backlog
    value: 8096
  - name: net.ipv4.tcp_slow_start_after_idle
    value: 0
  - name: net.ipv4.tcp_tw_reuse
    value: 1
  - name: net.ipv4.ip_local_port_range
    value: 10240 65535
  - name: net.ipv4.ip_local_reserved_ports
    value: 24224

ulimit_settings:
  - domain: root
    limit_type: soft
  - domain: root
    limit_type: hard
  - domain: "*"
    limit_type: soft
  - domain: "*"
    limit_type: hard

time_to_gz: 5
time_to_delete: 20

gzip_flush_interval:	"20s"
merged_flush_interval:	"10s"

plugin_log_level:
  zabbix_sender:  "debug"
  elasticsearch:  "debug"
