---

- name: install tcp_wrappers
  become: yes
  yum:
    name:               tcp_wrappers
    state:              latest
    disable_gpg_check:  yes

- name: Copy sshd@.service
  copy:
    src:    files/sshd@.service
    dest:   /etc/systemd/system/sshd@.service
    mode:   0644
    owner:  root
    group:  root

- name: Copy hosts.allow to /etc/hosts.allow
  copy:
    src:    files/hosts.allow-{{ release_env }}
    dest:   /etc/hosts.allow
    mode:   0644
    owner:  root
    group:  root

- name: Copy hosts.deny to /etc/hosts.deny
  copy:
    src:    files/hosts.deny
    dest:   /etc/hosts.deny
    mode:   0644
    owner:  root
    group:  root

# sshd.service の自動起動を設定しても他のサービスとの依存関係で起動してしまうため無意味
# - name: disable sshd
#   systemd:
#     name:     sshd.service
#     state:    stopped
#     enabled:  no

# - name: enable sshd.socket
#   systemd:
#     name:     sshd.socket
#     state:    started
#     daemon_reload: yes
#     enabled:  yes

# 既存設定に戻す
- name: enable sshd
  systemd:
    name:     sshd.service
    state:    started
    daemon_reload: yes
    enabled:  yes

- name: disable sshd.socket
  systemd:
    name:     sshd.socket
    state:    stopped
    enabled:  no

# スクリプト配置用ディレクトリ作成
- name: Create directory sshd_socket_start
  file: 
    path=/usr/local/app/script/sshd_socket_start
    state=directory 
    owner=root 
    group=root

# sshd.socket用のユニットファイルを配布する 実体はsshd.service を止めてsshd.socketを起動するもの
- name: Copy sshd_socket_start.sh
  copy:
    src:    files/sshd_socket_start.sh
    dest:   /usr/local/app/script/sshd_socket_start/
    mode:   0744
    owner:  root
    group:  root

- name: Copy sshd_socket_start.service
  copy:
    src:    files/sshd_socket_start.service
    dest:   /etc/systemd/system/
    mode:   0644
    owner:  root
    group:  root

# sshd.socket用のユニットファイルをenable化する

- name: enable sshd_socket_start
  systemd:
    name:     sshd_socket_start.service
    state:    started
    daemon_reload: yes
    enabled:  yes
  when: not ansible_check_mode

