# Sceptre Dev Environment Configuration

# AWS Basic Configuration
region: ap-northeast-1
project_code: aws-ses-migration-dev
environment: dev

# Stack References
stacks:
  base: base.yaml
  ses: phase-3-ses-byodkim.yaml
  security: security.yaml
  monitoring: monitoring.yaml

# Common Tags
tags:
  Environment: dev
  Project: aws-ses-migration
  ManagedBy: sceptre
  Owner: infrastructure-team
  CostCenter: IT-001
