# Monitoring Stack Configuration
template:
  type: file
  path: ../templates_dev/monitoring.yaml

dependencies:
  - dev/base.yaml
  - dev/phase-3-ses-byodkim.yaml

parameters:
  ProjectCode: aws-ses-migration
  Environment: development
  DomainName: goo.ne.jp

  # Alert thresholds
  SendSuccessRateThreshold: 95.0
  BounceRateThreshold: 5.0
  ComplaintRateThreshold: 0.1

  # Log retention periods
  RetentionDays: 90
  CloudWatchLogRetentionDays: 90

  # Lambda Configuration
  LambdaMemorySize: 256
  LambdaTimeout: 60
  LambdaRuntime: !stack_output dev/base.yaml::LambdaRuntime

  # Required parameters
  AllowedIPRanges:
    - 10.0.0.0/8
    - 192.168.1.0/24

  # Feature Flags
  EnableCustomMetrics: "false"
  EnableDataMasking: "true"
  EnableCloudWatchAlarms: "true"
  EnableInsightsQueries: "true"
  EnableTokyoRegionFeatures: "true"
  EnableJapaneseCompliance: "true"
  EnableJapaneseMonitoring: "true"
  EnableTokyoRegionMetrics: "true"
  EnableBYODKIMMonitoring: "true"

  # BYODKIM Configuration (Development)
  BYODKIMSelector: "gooid-21-dev"

  # CloudWatch Settings
  CloudWatchMetricNamespace: "ses-migration/development/Monitoring"
  CloudWatchDashboardName: "ses-migration-development-dashboard"

  # Output values from Base stack
  SNSTopicArn: !stack_output dev/base.yaml::NotificationTopicArn
  S3BucketName: !stack_output dev/base.yaml::RawLogsBucketName

  # Output values from SES stack
  SESLogGroupName: !stack_output dev/phase-3-ses-byodkim.yaml::SESLogGroupName

tags:
  Service: monitoring
  Component: cloudwatch
  Environment: dev
  Project: ses-migration
  ManagedBy: sceptre
  Owner: infrastructure-team
  CostCenter: IT-001
