# Phase 3: SES Configuration and BYODKIM Initialization for Development Environment
# Development environment shares EmailIdentity with production (goo.ne.jp)
# Key difference: Does NOT create EmailIdentity, uses existing prod EmailIdentity

template:
  type: file
  path: ../templates_dev/ses-configuration-dev.yaml

dependencies:
  - dev/phase-1-infrastructure-foundation.yaml
  - dev/phase-2-dkim-system.yaml

parameters:
  ProjectName: !stack_output dev/phase-1-infrastructure-foundation.yaml::ProjectName
  Environment: !stack_output dev/phase-1-infrastructure-foundation.yaml::Environment
  DomainName: !stack_output dev/phase-1-infrastructure-foundation.yaml::DomainName
  DKIMManagerFunctionArn: !stack_output dev/phase-2-dkim-system.yaml::DKIMManagerFunctionArn
  DKIMSeparator: gooid-21-dev  # Development selector

  # EmailIdentity Configuration (SHARED with production)
  # Development environment uses the same goo.ne.jp EmailIdentity as production
  # but with different BYODKIM selector to avoid conflicts
  SharedEmailIdentity: goo.ne.jp  # Reference to prod's EmailIdentity

  # Development-specific settings
  CloudWatchLogRetentionDays: 30  # Shorter retention for dev
  LambdaMemorySize: 256  # Lower memory for dev

tags:
  Service: ses
  Component: phase-3-ses-byodkim
  Environment: dev
  Project: ses-migration
  ManagedBy: sceptre
  Owner: development-team
  CostCenter: IT-DEV-001
  Production: false
  Critical: false
  Purpose: ses-configuration
  EmailIdentityOwner: production  # Indicates dependency on prod
