# Phase 1: Infrastructure Foundation for Development Environment
# Development environment configuration based on production setup
# Key difference: Uses dev-specific parameters and separate infrastructure

template_path: ../templates_dev/phase-1-infrastructure-foundation.yaml

parameters:
  # Required parameters matching template
  ProjectName: aws-ses-migration
  Environment: dev  # Changed to match template AllowedValues
  DomainName: goo.ne.jp
  DKIMSeparator: gooid-21-dev

  # Log retention settings for dev
  LogRetentionDays: 30
  LogsRetentionDays: 30
  LogsTransitionToIADays: 30
  LogsTransitionToGlacierDays: 90

  # Contact and configuration
  DNSTeamEmail: goo-idpay-sys@ml.nttdocomo.com
  LambdaRuntime: python3.13
  AccessLogDestinationBucket: service-logs-gooid-idhub

tags:
  Phase: "1-infrastructure-foundation"
  Purpose: "Complete infrastructure foundation"
  Environment: dev
