# Phase 6: Manual DNS Setup for Development Environment
# DNS records configuration for dev environment

template:
  type: file
  path: ../templates_dev/dns-setup-dev.yaml

dependencies:
  - dev/phase-5-dns-team-collaboration.yaml

parameters:
  ProjectName: !stack_output dev/phase-1-infrastructure-foundation.yaml::ProjectName
  Environment: dev  # Use dev for consistency
  DomainName: !stack_output dev/phase-1-infrastructure-foundation.yaml::DomainName
  DKIMSeparator: gooid-21-dev  # Development selector

  # Required from previous phases
  NotificationTopicArn: !stack_output dev/base.yaml::NotificationTopicArn
  KMSKeyArn: !stack_output dev/base.yaml::KMSKeyArn

  # DNS configuration for development
  DNSOperatorRole: arn:aws:iam::123456789012:role/DNSOperatorRole

  # Development-specific settings
  TTL: 300  # Shorter TTL for faster dev testing
  PriorityLevel: low  # Non-critical for production

  # Development team contact
  DNSContactEmail: !stack_output dev/phase-1-infrastructure-foundation.yaml::DNSTeamEmail
  TechnicalContactName: Development Team
  TechnicalContactEmail: !stack_output dev/phase-1-infrastructure-foundation.yaml::DNSTeamEmail

tags:
  Service: dns
  Component: phase-6-dns-setup
  Environment: dev
  Project: ses-migration
  ManagedBy: sceptre
  Owner: development-team
  CostCenter: IT-DEV-001
  Production: false
  Critical: false
  Purpose: development-dns
