# Phase 5: DNS Team Collaboration for Development Environment
# DNS team collaboration for dev environment

template:
  type: file
  path: ../templates_dev/dns-team-collaboration.yaml

dependencies:
  - dev/phase-4-dns-preparation.yaml

parameters:
  ProjectName: !stack_output dev/phase-1-infrastructure-foundation.yaml::ProjectName
  Environment: dev  # Use dev for consistency with actual infrastructure
  DKIMManagerFunctionArn: !stack_output dev/phase-2-dkim-system.yaml::DKIMManagerFunctionArn
  DNSTeamEmail: dev-team@goo.ne.jp  # Development team email
  SlackWebhookURL: ""  # Optional parameter

tags:
  Service: collaboration
  Component: phase-5-dns-team-collaboration
  Environment: dev
  Project: ses-migration
  ManagedBy: sceptre
  Owner: development-team
  CostCenter: IT-DEV-001
  Production: false
  Critical: false
  Purpose: dns-collaboration
