# Phase 4: DNS Preparation for Development Environment
# DNS preparation for dev BYODKIM selector

template:
  type: file
  path: ../templates_dev/dns-preparation.yaml

dependencies:
  - dev/phase-3-ses-byodkim.yaml

parameters:
  ProjectName: !stack_output dev/phase-1-infrastructure-foundation.yaml::ProjectName
  Environment: dev  # Use dev for consistency with actual infrastructure
  DomainName: !stack_output dev/phase-1-infrastructure-foundation.yaml::DomainName

  # Required from previous phases
  DKIMManagerFunctionArn: !stack_output dev/phase-2-dkim-system.yaml::DKIMManagerFunctionArn

tags:
  Service: dns
  Component: phase-4-dns-preparation
  Environment: dev
  Project: ses-migration
  ManagedBy: sceptre
  Owner: development-team
  CostCenter: IT-DEV-001
  Production: false
  Critical: false
  Purpose: dns-preparation
