---
#   #ログフォルダの権限変更
- name: ログフォルダの権限変更
  file:
    state: directory
    path: /var/log/httpd
    owner: root
    group: root
    mode: 0755

- name: Copy httpd.conf
  template:
    src: templates/httpd/{{ service_code }}/httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
    backup: yes 
    owner: root
    group: root
    mode: 0644
  notify:
    - httpd_hlp_restart_msg

- name: Copy http.conf
  template:
    src: templates/httpd/http.conf.j2
    dest: /etc/httpd/conf.d/http.conf
    backup: yes 
    owner: root
    group: root
    mode: 0644
  notify:
    - httpd_hlp_restart_msg

- name: Copy proxy.conf
  template:
    src: templates/httpd/proxy.conf.j2
    dest: /etc/httpd/conf.d/proxy.conf
    backup: yes 
    owner: root
    group: root
    mode: 0644
  notify:
    - httpd_hlp_restart_msg

- name: Copy ssl.conf
  template:
    src: templates/httpd/{{ service_code }}/ssl.conf.j2
    dest: /etc/httpd/conf.d/ssl.conf
    backup: yes 
    owner: root
    group: root
    mode: 0644
  notify:
    - httpd_hlp_restart_msg

- name: Copy 00-mpm.conf
  template:
    src: templates/httpd/00-mpm.conf.j2
    dest: /etc/httpd/conf.modules.d/00-mpm.conf
    backup: yes
    owner: root
    group: root
    mode: 0644

- name: Copy httpd.service
  template:
    src: templates/httpd/httpd.service.j2
    dest: /etc/systemd/system/httpd.service
    backup: yes 
    owner: root
    group: root
    mode: 0644
  when: release_env == "dev"
