---
- name: /etc/hostsの配布
  template:
    src: templates/{{ service_code }}/hosts-{{ release_env }}.j2
    dest: /etc/hosts
    backup: yes 
    owner: root
    group: root
    mode: 0644
  when: release_env == "pro"
