AWSTemplateFormatVersion: '2010-09-09'
Description: 'Phase 8: Basic DKIM Monitoring System (Simplified)'

Parameters:
  ProjectName:
    Type: String
    Description: Project name for resource naming
    Default: aws-ses-migration

  Environment:
    Type: String
    Description: Environment name
    AllowedValues:
      - dev
      - staging
      - prod
    Default: prod

  DomainName:
    Type: String
    Description: Domain name for monitoring
    Default: goo.ne.jp

Resources:
  # CloudWatch Log Group for Phase 8 monitoring
  Phase8LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${ProjectName}-${Environment}-phase8-monitoring'
      RetentionInDays: 30
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Phase
          Value: "8"

  # CloudWatch Alarm for DKIM Status Monitoring
  DKIMStatusAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${ProjectName}-${Environment}-dkim-status-alarm'
      AlarmDescription: 'Monitor DKIM certificate status'
      MetricName: 'DKIMStatus'
      Namespace: !Sub '${ProjectName}/${Environment}'
      Statistic: Average
      Period: 300
      EvaluationPeriods: 1
      Threshold: 0
      ComparisonOperator: LessThanThreshold
      TreatMissingData: notBreaching
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: "DKIM monitoring"

  # SNS Topic for Phase 8 notifications
  Phase8NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ProjectName}-${Environment}-phase8-notifications'
      DisplayName: 'Phase 8 DKIM Monitoring Notifications'
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Phase
          Value: "8"

  # CloudWatch Dashboard for Phase 8
  Phase8Dashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub '${ProjectName}-${Environment}-phase8-monitoring'
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "metrics": [
                  [ "${ProjectName}/${Environment}", "DKIMStatus" ],
                  [ ".", "CertificateExpiry" ]
                ],
                "view": "timeSeries",
                "stacked": false,
                "region": "ap-northeast-1",
                "title": "DKIM Certificate Status",
                "period": 300
              }
            },
            {
              "type": "log",
              "x": 0,
              "y": 6,
              "width": 24,
              "height": 6,
              "properties": {
                "query": "SOURCE '/aws/lambda/${ProjectName}-${Environment}-phase8-monitoring' | fields @timestamp, @message | sort @timestamp desc | limit 100",
                "region": "ap-northeast-1",
                "title": "Phase 8 Monitoring Logs",
                "view": "table"
              }
            }
          ]
        }

Outputs:
  Phase8LogGroupArn:
    Description: ARN of Phase 8 log group
    Value: !GetAtt Phase8LogGroup.Arn
    Export:
      Name: !Sub '${ProjectName}-${Environment}-phase8-log-group-arn'

  Phase8NotificationTopicArn:
    Description: ARN of Phase 8 notification topic
    Value: !Ref Phase8NotificationTopic
    Export:
      Name: !Sub '${ProjectName}-${Environment}-phase8-notification-topic-arn'

  DashboardURL:
    Description: URL to Phase 8 monitoring dashboard
    Value: !Sub 'https://console.aws.amazon.com/cloudwatch/home?region=ap-northeast-1#dashboards:name=${ProjectName}-${Environment}-phase8-monitoring'

  Status:
    Description: Phase 8 deployment status
    Value: "Phase 8 Basic Monitoring System Deployed Successfully"
