---
# 検証・商用共通の設定
- name: Make directory
  file: path={{ item }} state=directory owner=root group=root mode=0755
  with_items:
  - /etc/httpd_gbs
  - /var/www_gbs/
  - /db0/log/httpd_gbs
  - /var/www_gbs/cgi-bin
  - /etc/httpd_gbs/conf
  - /etc/httpd_gbs/conf.d
  - /etc/httpd_gbs/conf.modules.d

- name: Make directory 
  file: path={{ item }} state=directory owner=apache group=apache mode=0755
  with_items:
  - /var/www_gbs/html
  - /var/www_gbs/html/css
  - /var/www_gbs/html/js

- name: Link /var/log/httpd_gbs -> /db0/log/httpd_gbs
  file:
    state: link
    src: /db0/log/httpd_gbs
    dest: /var/log/httpd_gbs
    follow: no
  when: not ansible_check_mode

- name: Link /etc/httpd_gbs/logs -> ../../var/log/httpd_gbs
  file:
    state: link
    src:  ../../var/log/httpd_gbs
    dest: /etc/httpd_gbs/logs
    follow: no
  when: not ansible_check_mode

- name: Link /etc/httpd_gbs/modules -> ../../usr/lib64/httpd/modules
  file:
    state: link
    src: ../../usr/lib64/httpd/modules
    dest: /etc/httpd_gbs/modules
    follow: no
  when: not ansible_check_mode

- name: Link /etc/httpd_gbs/run -> /run/httpd$
  file:
    state: link
    src: /run/httpd
    dest: /etc/httpd_gbs/run
    follow: no
  when: not ansible_check_mode

- name: 起動スクリプト配置 
  template:
    src: templates/httpd_gbs/httpd_gbs.service.j2 
    dest: /etc/systemd/system/httpd_gbs.service
    owner: puppet
    group: puppet

- name: 起動スクリプト用の設定ファイル配置
  template:
    src: templates/httpd_gbs/httpd_gbs.j2
    dest: /etc/sysconfig/httpd_gbs
    owner: puppet
    group: puppet

- name: Copy id.css
  template:
    src: templates/httpd_gbs/id.css.j2
    dest: /var/www_gbs/html/css/id.css
    owner: apache
    group: apache

- name: Copy login.css
  template:
    src: templates/httpd_gbs/login.css.j2
    dest: /var/www_gbs/html/css/login.css

- name: Copy error.html.utf8
  template:
    src: templates/httpd_gbs/error.html.utf8.j2
    dest: /var/www_gbs/html/error.html.utf8
    owner: apache
    group: apache

- name: Copy favicon.ico
  copy:
    src: files/httpd_gbs/favicon.ico
    dest: /var/www_gbs/html/favicon.ic
    remote_src: no
    owner: apache
    group: apache
  when: release_env == "pro"

- name: Copy mente.html
  template:
    src: templates/httpd_gbs/mente.html.j2
    dest: /var/www_gbs/html/mente.html
    owner: apache
    group: apache

- name: httpd.confの配布
  template:
    src: templates/httpd_gbs/httpd.conf.j2
    dest: /etc/httpd_gbs/conf/httpd.conf
  notify:
      - httpd_gbs_web_restart_msg

- name: external-maintenance.confの配布
  template:
    src: templates/httpd_gbs/external-maintenance.conf.j2
    dest: /etc/httpd_gbs/conf/external-maintenance.conf
  notify:
      - httpd_gbs_web_restart_msg

- name: Copy acl-servers.conf
  template:
    src: templates/httpd_gbs/acl-servers.conf-{{ release_env }}.j2
    dest: /etc/httpd_gbs/conf/acl-servers.conf
    owner: root
    group: root
    mode: 0644
  notify:
      - httpd_gbs_web_restart_msg

- name: maintenance.confの配布
  template:
    src: templates/httpd_gbs/maintenance.conf.j2 
    dest: /etc/httpd_gbs/conf/maintenance.conf
  notify:
      - httpd_gbs_web_restart_msg

- name: stop_goods.confの配布
  template:
    src: templates/httpd_gbs/stop_goods.conf.j2
    dest: /etc/httpd_gbs/conf/stop_goods.conf
  notify:
      - httpd_gbs_web_restart_msg

- name: rewrite.confの配布
  template:
    src: templates/httpd_gbs/rewrite.conf.j2
    dest: /etc/httpd_gbs/conf/rewrite.conf
  notify:
      - httpd_gbs_web_restart_msg

- name: magicの配布
  template:
    src: templates/httpd_gbs/magic.j2
    dest: /etc/httpd_gbs/conf/magic
  notify:
      - httpd_gbs_web_restart_msg

- name: http.confの配布
  # roles/katemusha/templates に値を設定します。
  vars:
    kagemusha_port: "{{ httpd_gbs_port }}"
  template:
    src: templates/httpd_gbs/http.conf.j2
    dest: /etc/httpd_gbs/conf.d/http.conf
  notify:
      - httpd_gbs_web_restart_msg

- name: access_control.confの配布
  template:
    src: templates/httpd_gbs/access_control-{{ release_env }}.conf.j2 
    dest: /etc/httpd_gbs/conf.d/access_control.conf
  notify:
      - httpd_gbs_web_restart_msg

- name: nocache.confの配布
  template:
    src: templates/httpd_gbs/nocache.conf.j2
    dest: /etc/httpd_gbs/conf.d/nocache.conf
  notify:
      - httpd_gbs_web_restart_msg

- name: proxy_ajp.confの配布
  template:
    src: templates/httpd_gbs/proxy_ajp.conf.j2
    dest: /etc/httpd_gbs/conf.d/proxy_ajp.conf
  notify:
      - httpd_gbs_web_restart_msg

- name: p3p.confの配布
  template:
    src: templates/httpd_gbs/p3p.conf.j2
    dest: /etc/httpd_gbs/conf.d/p3p.conf
  notify:
      - httpd_gbs_web_restart_msg

# このファイルはAnsible Playbookの管理下以外の箇所、Jenkinsで変更されることがある。
# ファイルが存在しない場合のみ、配布する。
- name: gbs_spring.confの存在を確認
  stat:
    path: /etc/httpd_gbs/conf.d/gbs_spring.conf
  register: gbs_spring

# このファイルはAnsible Playbookの管理下以外の箇所、Jenkinsで変更されることがある。
# ファイルが存在しない場合のみ、配布する。
- name: gbs_spring.confの配布
  template:
    src: templates/httpd_gbs/gbs_spring.conf.j2
    dest: /etc/httpd_gbs/conf.d/gbs_spring.conf
  when: not gbs_spring.stat.exists

- name: 00-base.confの配布
  template:
    src: templates/httpd_gbs/00-base.conf.j2
    dest: /etc/httpd_gbs/conf.modules.d/00-base.conf

- name: 00-mpm.confの配布
  template:
    src: templates/httpd_gbs/00-mpm.conf.j2
    dest: /etc/httpd_gbs/conf.modules.d/00-mpm.conf

- name: 00-proxy.confの配布
  template:
    src: templates/httpd_gbs/00-proxy.conf.j2
    dest: /etc/httpd_gbs/conf.modules.d/00-proxy.conf

- name: 00-ssl.confの配布
  template:
    src: templates/httpd_gbs/00-ssl.conf.j2
    dest: /etc/httpd_gbs/conf.modules.d/00-ssl.conf

- name: 00-systemd.confの配布
  template:
    src: templates/httpd_gbs/00-systemd.conf.j2
    dest: /etc/httpd_gbs/conf.modules.d/00-systemd.conf

- name: 01-cgi.confの配布
  template:
    src: templates/httpd_gbs/01-cgi.conf.j2
    dest: /etc/httpd_gbs/conf.modules.d/01-cgi.conf

