---
# Tomcat 9.0用の変更。
# Tomcatのバージョンが9に上がったので設定の変更が必要になった
# ディレクトリのパーミッションを0750から0755へ変更
- name: Create directories
  file: 
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
    "{{ directories }}"

# Tomcat 9.0用の変更 
- name: /opt/tomcat/bin配下にある*.sh以外を0644に設定する
  file:
    path: /opt/tomcat/bin/{{ item }}
    state: file
    mode: 0644
  loop:
    "{{ other_bin_files }}"

# Tomcat 9.0用の変更 
# /opt/tomcat/bin/*.shを0755に設定する
- name: chmod 0755 /opt/tomcat/bin/*.sh
  file:
    path: /opt/tomcat/bin/{{ item }}
    state: file
    mode: 0755
  loop:
    "{{ shell_scripts }}"

# Tomcat 9.0用の変更 
# /opt/tomcat/lib/*を0644に設定する
- name: chmod 0644 /opt/tomcat/lib/*
  file:
    path: /opt/tomcat/lib/{{ item }}
    state: file
    mode: 0644
  loop:
    "{{ jar_files }}"

## Tomcat 9.0用の変更 
# webサーバだけは  /usr/local/tomcat/idc/bin
# その他のサーバは /usr/local/tomcat/bin
- name: /usr/local/tomcat/bin 配下にある*.sh以外を0644に設定する
  file:
    path: >-
      {%- if inventory_hostname_short is regex("-web-\d{3}$") -%} /usr/local/tomcat/idc/bin/{{ item }}
      {%- else -%} /usr/local/tomcat/bin/{{ item }}
      {%- endif -%}
    state: file
    mode: 0644
  loop:
    "{{ other_bin_files }}"

# Tomcat 9.0用の変更 
# webサーバだけは  /usr/local/tomcat/idc/bin
# その他のサーバは /usr/local/tomcat/bin
- name: chmod 0755 /usr/local/tomcat/bin/*.sh
  file:
    path: >-
      {%- if inventory_hostname_short is regex("-web-\d{3}$") -%} /usr/local/tomcat/idc/bin/{{ item }}
      {%- else -%} /usr/local/tomcat/bin/{{ item }}
      {%- endif -%}
    state: file
    mode: 0755
  loop:
    "{{ shell_scripts }}"

