---
- name: gbs muleのrestart_msg
  debug:
    msg: "{{ commands }}"
  listen: gbs_mule_restart_msg
    
  vars:
    commands:
      - "  注意：configが書き換わりました。gbs muleを手動で再起動してください。 "
      - "  sudo systemctl restart gbs_mule  "
      - "  sudo systemctl status gbs_mule   "

