AWSTemplateFormatVersion: '2010-09-09'
Description: 'IAM Policy for CloudWatch Logs Agent'

Parameters:
  ProjectName:
    Type: String
    Default: poc
    Description: Name of the project

Resources:
  CloudWatchAgentPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub ${ProjectName}-cloudwatch-agent-policy
      Description: Policy to allow CloudWatch Logs Agent to send logs and retrieve configuration from SSM
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          # CloudWatch Logs permissions
          - Sid: CloudWatchLogsAccess
            Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - logs:DescribeLogStreams
              - logs:DescribeLogGroups
            Resource:
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/ec2/*
              - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/ec2/*:log-stream:*

          # SSM Parameter Store permissions for agent configuration
          - Sid: SSMParameterAccess
            Effect: Allow
            Action:
              - ssm:GetParameter
              - ssm:GetParameters
              - ssm:PutParameter
            Resource:
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/AmazonCloudWatch-*
              - !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${ProjectName}/cloudwatch-agent/*

          # EC2 metadata access for instance information
          - Sid: EC2MetadataAccess
            Effect: Allow
            Action:
              - ec2:DescribeTags
              - ec2:DescribeInstances
              - ec2:DescribeVolumes
            Resource: '*'

Outputs:
  PolicyArn:
    Description: ARN of the CloudWatch Agent policy
    Value: !Ref CloudWatchAgentPolicy
    Export:
      Name: !Sub ${ProjectName}-cloudwatch-agent-policy-arn
