---

# 個人情報を含むディレクトリはrbashユーザーから閲覧できないよう拡張ACLを設定します
# backlogチケット：https://bklg.docomo-common.com/backlog/view/GOOID-954
# 参考ページ：https://qiita.com/hana_shin/items/ec51f2d1ca5599293256

- name: Set ACL to deny access for rbash group to /var/log/app
  acl:
    path: /var/log/app
    entity: g-gooid_rbash
    etype: group
    permissions: '0'
    state: present
  when: server_role in ['web','hlp','batch','edb','msg','oidc']

- name: Set ACL to deny access for rbash group to /db0
  acl:
    path: /db0
    entity: g-gooid_rbash
    etype: group
    permissions: '0'  
    state: present
  when: server_role in ['batch','fgw','log']

