---
- name: Docker packages are no longer required
  ansible.builtin.dnf:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin

- name: Install container-tools module as Podman
  ansible.builtin.dnf:
    name: "@container-tools"
    state: present
    # update_cache: true
