# mdb

# galeraクラスタ設定
galera_cluster_name: GOOID_GALERA_DB
galera_node_name: gooid_pro_db_1
galera_func: galera
galera_addr1: 10.23.102.100
galera_addr2: 10.23.102.101
galera_addr3: 10.23.102.102
galera_addr4: 10.23.102.80
galera_addr5: 10.23.102.81

# Galera Cluster のLeaderであるか？
# 実際に動的にステータスは見ずに、静的に定義するのみ
# これがtrueの場合、Clusterが構築されていると前提をおいた上で、
# MySQL GRANT定義などを行ったりする。
galera_cluster_leader: true
