# sdb

# galeraクラスタ設定
galera_cluster_name: GOOID_GALERA_DB
galera_node_name: gooid_pro_db_5
galera_func: galera
galera_addr1: 10.23.102.81
galera_addr2: 10.23.102.100
galera_addr3: 10.23.102.101
galera_addr4: 10.23.102.102
galera_addr5: 10.23.102.80

