# edb

# 商用・検証環境ともに、プライベートIPでアクセスされます。
# 商用： 退避gooIDの復元手順（リモートワーク編）- 2022 : https://bit.ly/3Sy5kcA
# 検証： SSH Port Forwarding にて。
edb_httpd_fqdn: "{{ ansible_ens2.ipv4.address }}"
edb_httpd_port: 80
edb_httpd_logformat_type: combined_gooidc
edb_httpd_logformat: '"%h %l %u %t %D \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\""'

# proxysql設定
edb_proxysql:
  #
  # 退避DBのノードをここに定義します。
  #
  #   - ここはGalera Clusterではなく、通常のReplicationを採用しています。
  #   - ノードは最小1台、最大で2大まで定義できます。
  archive:
    nodes:
      # edb (DB client) <-> edb (DB server) は、裏NICで通信できるため、
      # 少しでもサービスNWの帯域を使わないよう "-b" を使います。
      - gooid-21-pro-edb-001-b
      - gooid-21-pro-edb-002-b
  #
  # gooIDのサービスDBのノードをここに定義します。
  #
  #   - ここはGalera Clusterです。
  #   - edb上のバッチで、前述の「退避DB」と、ここで定義する「サービスDB」双方に作用し、参照・更新されます。
  # 
  # 1つ目のノードは、平常時の単一の書き込みノードになります。
  # 2～3つ目のノードは、（正常時）参照用ノード ／ （故障時）1つ目のノードが故障した際、単一書き込みノードに昇格します。
  # 4つ以上定義すると、4と5ノード目は、参照専用のノード（＝決して書き込みノードに昇格しない）となります。
  #
  # 詳細は、Jinja2テンプレート `roles/proxysql/templates/edb/proxysql.cnf.j2` を参照してください。
  service:
    nodes:
      # edb (DB client) <-> mdb,sdb (DB server) は、裏NICで通信できるため、
      # 少しでもサービスNWの帯域を使わないよう "-b" を使います。
      - gooid-21-pro-mdb-001-b
      - gooid-21-pro-mdb-002-b
      - gooid-21-pro-mdb-003-b
      - gooid-21-pro-sdb-001-b
      - gooid-21-pro-sdb-002-b

# mule-config.xml.j2で変数を参照
gbs_mule_host: 202.217.73.241:80

# 退避DB用MySQLインスタンス ([mysqld1]) のみから参照されます。
galera_func: "replication"

# httpd_edbのhttp.conf.j2で参照する変数
# BalancerMember ajp://{{ ajp1 }}:8009 keepalive=on route={{ route1 }} loadfactor=1
# BalancerMember ajp://{{ ajp2 }}:8009 keepalive=on route={{ route2 }} status=+H
proxypass_balancer: gooid-21-pro-edb-000
ajp1: gooid-21-pro-edb-001-b
ajp2: "{{ inventory_hostname_short ~ '-b' }}"
route1: gooid-21-pro-edb-001
route2: "{{ inventory_hostname_short }}"
