AWSTemplateFormatVersion: '2010-09-09'
Description: 'SES Sandbox Email Verification - Add verified email addresses for testing'

Parameters:
  ProjectName:
    Type: String
    Description: Project name for resource naming
    Default: aws-ses-migration

  Environment:
    Type: String
    Description: Environment name
    AllowedValues:
      - development
      - staging
      - production
      - prod
      - dev
    Default: prod

  # Test Email Configuration
  TestEmailAddress:
    Type: String
    Description: Email address to verify for sandbox testing
    Default: goo-idpay-sys@ml.nttdocomo.com

  # Reference to existing SES Configuration Set for consistent tagging
  SESConfigurationSetName:
    Type: String
    Description: Name of the existing SES Configuration Set (for reference)

Resources:
  # Verified Email Identity for Sandbox Testing
  VerifiedTestEmailIdentity:
    Type: AWS::SES::EmailIdentity
    Properties:
      EmailIdentity: !Ref TestEmailAddress
      ConfigurationSetAttributes:
        ConfigurationSetName: !Ref SESConfigurationSetName
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-test-email-identity"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: "Sandbox-Testing"
        - Key: VerifiedFor
          Value: "SandboxMode"

  # CloudWatch Log Group for test email events
  TestEmailLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/ses/test-emails/${ProjectName}-${Environment}"
      RetentionInDays: 30
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-test-email-logs"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment

Outputs:
  VerifiedTestEmailAddress:
    Description: Verified test email address for sandbox mode
    Value: !Ref TestEmailAddress
    Export:
      Name: !Sub "${ProjectName}-${Environment}-verified-test-email"

  TestEmailIdentityArn:
    Description: ARN of the verified test email identity
    Value: !Sub "arn:aws:ses:${AWS::Region}:${AWS::AccountId}:identity/${TestEmailAddress}"
    Export:
      Name: !Sub "${ProjectName}-${Environment}-test-email-identity-arn"

  SandboxTestingStatus:
    Description: Status message for sandbox testing setup
    Value: !Sub "Sandbox testing enabled with verified email: ${TestEmailAddress}"
    Export:
      Name: !Sub "${ProjectName}-${Environment}-sandbox-status"

  TestEmailLogGroupName:
    Description: Name of the test email log group
    Value: !Ref TestEmailLogGroup
    Export:
      Name: !Sub "${ProjectName}-${Environment}-test-email-log-group"
