---

- name: enable powertools repo
  command: dnf config-manager --set-enabled powertools

# インストール済みなので不要（但しGPGキーがインストールされていないので別途対応が必要）
# rpmkeys --import https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
# - name: install epel-release
  # dnf:
    # name: epel-release

# この後作成されたCentOS-Gluster-10.repo をRocky Linux 向けに修正する必要がある
# - name: install centos-release-gluster10
#   dnf:
#     name: centos-release-gluster10
          
- name: install glusterfs-server
  dnf:
    name: "{{ packages }}"
  vars:
    packages:
      - glusterfs 
      - glusterfs-libs 
      - glusterfs-server

- name: enabled glusterfsd
  systemd:
    name: glusterfsd.service
    state: started 
    enabled: yes

# enable が必要かは要確認
- name: enabled glusterd
  systemd:
    name: glusterd.service
    state: started 
    enabled: yes




