---

# GlusterFSクラスタ間でピアを張る
- name:  gluster peer
  command: gluster peer probe gooid-30-dev-container-002
  when: inventory_hostname == 'gooid-30-dev-container-001'

# GlusterFSで使用するディレクトリ作成
- name: create brick directory
  file:
    path: "/data/glusterfs/brick1"
    state: directory
    owner: "root"
    group: "root"
    mode: "775"


# # 複製ボリュームの作成（データは両方のサーバーに複製される）
# 今回は検証環境なのでforceオプションを付けて作成したが本来はルートパーティション上に作るべきではなく、専用のディスクをマウントするべき
# - name: gluster volume create
#   expect:
#     command: >
#       gluster volume create gfs-volume replica 2
#       gooid-30-dev-container-001:/data/glusterfs/brick1
#       gooid-30-dev-container-002:/data/glusterfs/brick1 force
#     responses:
#       "\\(y/N\\)": y
#   when: inventory_hostname == 'gooid-30-dev-container-001'

# # ボリューム起動
# - name: gluster volume start
#   command:  gluster volume start gfs-volume
#   when: inventory_hostname == 'gooid-30-dev-container-001'


