--- 
- name: /usr/local/tomcat/conf へ配布
  copy:
    src: files/conf/{{ item }}
    dest: >- 
      {%- if inventory_hostname_short is regex("-web-\d{3}$") -%} /usr/local/tomcat/idc/conf/{{ item }}
      {%- else -%} /usr/local/tomcat/conf/{{ item }}
      {%- endif -%}
    owner: tomcat
    group: tomcat
  loop: 
    - catalina.policy
    - catalina.properties
    - jaspic-providers.xml
    - jaspic-providers.xsd
    - logging.properties
