- name: Download tomcat
  get_url:
    url: "{{ remote_repo_url }}/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: /tmp
    use_proxy: yes
  

- name: tomcatが既にインストール済みか確認
  stat:
    path: /opt/apache-tomcat-{{ tomcat_version }}/bin
  register: result

# tomcatがインストールされていなければ展開する
- name: Unarchive apache-tomcat-{{ tomcat_version }}.tar.gz 
  unarchive:
    src: /tmp/apache-tomcat-{{ tomcat_version }}.tar.gz 
    dest: /opt
    remote_src: yes
  when: not result.stat.exists and not ansible_check_mode

# binへファイルを配布する
- import_tasks: copy_bin.yml

# confへファイルを配布する
- import_tasks: copy_conf.yml
