---
# edb, hlp, msg, webサーバ共通設定
- name: Make /usr/local/tomcat
  file: path={{ item }} state=directory owner=tomcat group=tomcat
  loop:
    - /usr/local/tomcat

# edb, hlp, msg, webサーバ共通設定
- name: Make /opt/apache-tomcat-{{ tomcat_version }}
  file: path={{ item }} state=directory owner=root group=root
  loop:
    - /opt/apache-tomcat-{{ tomcat_version }}

# webサーバ設専用定
- name: Make directories
  file: path={{ item }} state=directory owner=tomcat group=tomcat
  loop:
    - /db0/log/tomcat
  when: inventory_hostname_short is regex("-web-\d{3}$")

# webサーバ設専用定
- name: Link /var/log/tomcat -> /db0/log/tomcat
  file:
    state: link
    src: /db0/log/tomcat
    dest: /var/log/tomcat
    owner: root
    group: root
    follow: no     # SymLinkのオーナーはrootに設定
  when: inventory_hostname_short is regex("-web-\d{3}$") and not ansible_check_mode

# webサーバ専用にディレクトリを作成
- name: Make directories
  file: path={{ item }} state=directory owner=tomcat group=tomcat
  loop:
    - /var/log/tomcat/idc
    - /usr/local/tomcat/idc
    - /usr/local/tomcat/idc/bin
    - /usr/local/tomcat/idc/conf
  when: inventory_hostname_short is regex("-web-\d{3}$")

# edb, hlp, msgサーバ用にディレクトリを作成
- name: Make directories
  file: path={{ item }} state=directory owner=tomcat group=tomcat
  loop:
    - /var/log/tomcat
    - /usr/local/tomcat/bin
    - /usr/local/tomcat/conf
  when: not inventory_hostname_short is regex("-web-\d{3}$")

# edb, hlp, msg, webサーバ共通設定
- name: Link /opt/tomcat -> /opt/apache-tomcat-{{ tomcat_version }}
  file:
    state: link
    src: /opt/apache-tomcat-{{ tomcat_version }}
    dest: /opt/tomcat
    owner: tomcat
    group: tomcat
    follow: no      # SymLinkのオーナーはtomcatに設定
  when: not ansible_check_mode

# webサーバ設専用定
- name: Link /usr/local/tomcat/idc/logs -> /var/log/tomcat/idc
  file:
    state: link
    src: /var/log/tomcat/idc
    dest: /usr/local/tomcat/idc/logs
  when: inventory_hostname_short is regex("-web-\d{3}$") and not ansible_check_mode

# edb, hlp, msgサーバ設定
- name: Link /usr/local/tomcat/logs -> /var/log/tomcat
  file:
    state: link
    src: /var/log/tomcat
    dest: /usr/local/tomcat/logs
  when: not inventory_hostname_short is regex("-web-\d{3}$") and not ansible_check_mode

