# Phase 7: DNS Configuration Validation and DKIM Activation Phase
# Steps 21-25: DNS propagation check, DKIM activation, success logging, completion status saving

template:
  type: file
  path: dns-validation-dkim-activation.yaml

parameters:
  ProjectName: !stack_output prod/phase-1-infrastructure-foundation.yaml::ProjectName
  Environment: !stack_output prod/phase-1-infrastructure-foundation.yaml::Environment
  DKIMManagerFunctionArn: !stack_output prod/phase-2-dkim-system.yaml::DKIMManagerFunctionArn
  DomainName: !stack_output prod/phase-1-infrastructure-foundation.yaml::DomainName

dependencies:
  - prod/phase-1-infrastructure-foundation.yaml
  - prod/phase-2-dkim-system.yaml
  - prod/phase-3-ses-byodkim.yaml
  - prod/phase-4-dns-preparation.yaml
  - prod/phase-5-dns-team-collaboration.yaml

tags:
  Phase: "7-dns-validation-dkim-activation"
  Purpose: "DNS validation and DKIM activation"
  Environment: prod
