template:
  type: file
  path: ses-kinesis-integration.yaml
stack_name: aws-ses-migration-prod-ses-kinesis-integration
parameters:
  # Project Configuration
  ProjectName: aws-ses-migration
  Environment: prod

  # Kinesis Integration
  KinesisStreamArn: !stack_output prod/enhanced-kinesis.yaml::UnifiedDataStreamArn
  KinesisStreamName: !stack_output prod/enhanced-kinesis.yaml::UnifiedDataStreamName

  # SNS Integration (will be created by this stack)
  SNSTopicArn: ""
  SESConfigurationSetName: !stack_output prod/phase-3-ses-byodkim.yaml::ConfigurationSetName

  # Feature Flags
  EnableKinesisLogging: "true"

dependencies:
  - prod/enhanced-kinesis.yaml
  - prod/phase-3-ses-byodkim.yaml
