---

- name: Create Elasticsearch certs directory
  file:
    path: /etc/td-agent/certs/ca
    state: directory
    owner: root
    group: root
    mode: 0750

- name: Copy Elasticsearch cert
  copy:
    src:  ~/very_secure_dir/elastic.crt
    dest: /etc/td-agent/certs/ca/http_ca.crt
    owner: root
    group: root
    mode: 0640
  notify: Restart td-agent
