AWSTemplateFormatVersion: '2010-09-09'
Description: 'DNS configuration preparation for DKIM'

Parameters:
  ProjectName:
    Type: String
    Description: Project name for resource naming
    Default: aws-ses-migration

  Environment:
    Type: String
    Description: Environment name
    AllowedValues:
      - development
      - staging
      - production
      - prod
      - dev
    Default: development

  DKIMManagerFunctionArn:
    Type: String
    Description: ARN of the DKIM Manager Lambda function

  DomainName:
    Type: String
    Description: Domain name for DKIM
    Default: goo.ne.jp

Resources:
  # EventBridge Rule to trigger Phase 4 execution
  Phase4TriggerRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "${ProjectName}-${Environment}-phase-4-trigger"
      Description: "Trigger Phase 4: DNS preparation"
      State: ENABLED
      EventPattern:
        source: ["aws.byodmim"]
        detail-type: ["Phase 4 Trigger"]
        detail:
          phase: ["4"]
          environment: [!Ref Environment]
          project: [!Ref ProjectName]
      Targets:
        - Arn: !Ref DKIMManagerFunctionArn
          Id: "DKIMManagerPhase4Target"
          Input: !Sub |
            {
              "phase": "4",
              "action": "phase_manager",
              "domain": "${DomainName}",
              "dkimSeparator": "gooid-21-pro",
              "environment": "${Environment}",
              "projectName": "${ProjectName}"
            }

  # Lambda permission for EventBridge
  DKIMManagerEventBridgePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DKIMManagerFunctionArn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt Phase4TriggerRule.Arn

Outputs:
  Phase4TriggerRuleArn:
    Description: ARN of the Phase 4 trigger EventBridge rule
    Value: !GetAtt Phase4TriggerRule.Arn
    Export:
      Name: !Sub "${ProjectName}-${Environment}-phase-4-trigger-arn"

  Phase4Status:
    Description: Phase 4 DNS preparation status
    Value: "Ready for Phase 4 execution"
    Export:
      Name: !Sub "${ProjectName}-${Environment}-phase-4-status"
