AWSTemplateFormatVersion: '2010-09-09'
Description: 'SES configuration for development environment (EmailIdentity shared with production)'

Parameters:
  ProjectName:
    Type: String
    Description: Project name for resource naming
    Default: aws-ses-migration

  Environment:
    Type: String
    Description: Environment name
    AllowedValues:
      - development
      - dev
    Default: development

  DomainName:
    Type: String
    Description: Domain name for email identity (shared with production)
    Default: goo.ne.jp

  SharedEmailIdentity:
    Type: String
    Description: EmailIdentity shared with production environment
    Default: goo.ne.jp

  DKIMManagerFunctionArn:
    Type: String
    Description: ARN of the DKIM Manager Lambda function

  DKIMSeparator:
    Type: String
    Description: DKIM separator prefix for development environment
    Default: gooid-21-dev

  CloudWatchLogRetentionDays:
    Type: Number
    Description: CloudWatch logs retention period (days)
    Default: 30
    MinValue: 1
    MaxValue: 2555

  LambdaMemorySize:
    Type: Number
    Description: Lambda function memory size (MB)
    Default: 256
    AllowedValues: [128, 256, 512, 1024, 1536, 2048, 3008]

Resources:
  # NOTE: EmailIdentity is NOT created in dev environment
  # Dev environment uses the existing EmailIdentity from production (goo.ne.jp)
  # Only Configuration Set and related resources are created

  # Configuration Set for email sending (development environment)
  ConfigurationSet:
    Type: AWS::SES::ConfigurationSet
    Properties:
      Name: !Sub "${ProjectName}-${Environment}-config-set"
      ReputationOptions:
        ReputationMetricsEnabled: true
      SendingOptions:
        SendingEnabled: true
      SuppressionOptions:
        SuppressedReasons:
          - BOUNCE
          - COMPLAINT
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-config-set"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: "Development configuration set"
        - Key: EmailIdentitySource
          Value: "shared-with-production"

  # Event Destination for bounce/complaint tracking (development)
  EventDestination:
    Type: AWS::SES::ConfigurationSetEventDestination
    Properties:
      ConfigurationSetName: !Ref ConfigurationSet
      EventDestination:
        Name: !Sub "${ProjectName}-${Environment}-event-destination"
        Enabled: true
        MatchingEventTypes:
          - bounce
          - complaint
          - delivery
          - send
          - reject
          - open
          - click
        CloudWatchDestination:
          DimensionConfigurations:
            - DimensionName: "MessageTag"
              DimensionValueSource: "messageTag"
              DefaultDimensionValue: "development"
            - DimensionName: "Environment"
              DimensionValueSource: "messageTag"
              DefaultDimensionValue: !Ref Environment

  # CloudWatch Log Group for SES events (development)
  SESLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/ses/${ProjectName}-${Environment}"
      RetentionInDays: !Ref CloudWatchLogRetentionDays
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${Environment}-ses-logs"
        - Key: Project
          Value: !Ref ProjectName
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: "Development SES logging"

  # EventBridge rule to trigger phased DKIM setup for development
  DKIMPhaseManagerRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "Trigger phased DKIM setup for development environment"
      EventPattern:
        source: ["aws.cloudformation"]
        detail-type: ["CloudFormation Stack Status Change"]
        detail:
          status-details:
            status: ["CREATE_COMPLETE", "UPDATE_COMPLETE"]
          stack-name: [!Ref "AWS::StackName"]
      State: ENABLED
      Targets:
        - Arn: !Ref DKIMManagerFunctionArn
          Id: "DKIMPhaseManagerDev"
          Input: !Sub |
            {
              "phase": "3",
              "action": "phase_manager",
              "domain": "${DomainName}",
              "sharedEmailIdentity": "${SharedEmailIdentity}",
              "dkimSeparator": "${DKIMSeparator}",
              "environment": "${Environment}",
              "projectName": "${ProjectName}",
              "isDevelopment": true,
              "emailIdentityShared": true
            }

  # Lambda permission for EventBridge (development)
  DKIMManagerEventBridgePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref DKIMManagerFunctionArn
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt DKIMPhaseManagerRule.Arn

  # Custom Resource to validate shared EmailIdentity exists
  EmailIdentityValidator:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !Ref DKIMManagerFunctionArn
      CustomResourceType: EmailIdentityValidator
      EmailIdentity: !Ref SharedEmailIdentity
      Environment: !Ref Environment
      ValidationType: SharedEmailIdentityCheck

Outputs:
  # EmailIdentity name (referenced from production)
  EmailIdentityName:
    Description: Name of the shared SES Email Identity (from production)
    Value: !Ref SharedEmailIdentity
    Export:
      Name: !Sub "${ProjectName}-${Environment}-email-identity-name"

  ConfigurationSetName:
    Description: Name of the SES Configuration Set (development)
    Value: !Ref ConfigurationSet
    Export:
      Name: !Sub "${ProjectName}-${Environment}-config-set-name"

  SESLogGroupName:
    Description: Name of the SES log group (development)
    Value: !Ref SESLogGroup
    Export:
      Name: !Sub "${ProjectName}-${Environment}-ses-log-group-name"

  SESDomainName:
    Description: Configured domain name for SES (shared)
    Value: !Ref DomainName
    Export:
      Name: !Sub "${ProjectName}-${Environment}-ses-domain-name"

  SharedEmailIdentityName:
    Description: Shared EmailIdentity name from production
    Value: !Ref SharedEmailIdentity
    Export:
      Name: !Sub "${ProjectName}-${Environment}-shared-email-identity"

  DKIMSeparatorWithEnv:
    Description: DKIM separator for development environment
    Value: !Sub "${DKIMSeparator}"
    Export:
      Name: !Sub "${ProjectName}-${Environment}-dkim-separator"

  DKIMPhaseManagerRuleArn:
    Description: ARN of the DKIM phase manager EventBridge rule (development)
    Value: !GetAtt DKIMPhaseManagerRule.Arn
    Export:
      Name: !Sub "${ProjectName}-${Environment}-dkim-phase-manager-rule"

  EnvironmentType:
    Description: Environment type indicator
    Value: !Sub "${Environment}-shared-emailidentity"
    Export:
      Name: !Sub "${ProjectName}-${Environment}-environment-type"

  ProductionDependency:
    Description: Indicates dependency on production EmailIdentity
    Value: !Sub "depends-on-production-${SharedEmailIdentity}"
    Export:
      Name: !Sub "${ProjectName}-${Environment}-production-dependency"
