AWSTemplateFormatVersion: '2010-09-09'
Description: 'POC EC2 Template - Simplified with Lambda auto-tagging and monitoring'

Parameters:
  # Network Configuration
  VPCId:
    Type: String
    Description: VPC ID for EC2 instances

  PrivateSubnets:
    Type: CommaDelimitedList
    Description: List of private subnet IDs for EC2 placement

  SecurityGroupId:
    Type: String
    Description: Security group ID for EC2 instances

  # Instance Configuration
  InstanceType:
    Type: String
    Default: t3.medium
    AllowedValues:
      - t3.small
      - t3.medium
      - t3.large
    Description: EC2 instance type

  KeyPairName:
    Type: String
    Default: ""
    Description: EC2 Key Pair name (optional, SSM Session Manager recommended)

  # Auto Scaling Configuration
  DesiredCapacity:
    Type: Number
    Default: 3
    MinValue: 3
    MaxValue: 3
    Description: Fixed number of instances (3 - one per AZ)

  # Application Configuration
  ApplicationName:
    Type: String
    Default: poc-web
    Description: Application name for tagging

  Environment:
    Type: String
    Default: poc
    AllowedValues:
      - dev
      - stg
      - poc
      - prod
    Description: Environment name

  # ALB Target Group ARN (passed from ALB stack)
  TargetGroupArn:
    Type: String
    Description: ALB Target Group ARN for health check

Conditions:
  HasKeyPair: !Not [!Equals [!Ref KeyPairName, ""]]

Resources:
  # IAM Role for EC2 instances (SSM Session Manager + Systems Manager)
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-ec2-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        # SSM Session Manager policy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        # Patch management policy
        - arn:aws:iam::aws:policy/AmazonSSMPatchAssociation
        # CloudWatch Logs policy
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      Policies:
        - PolicyName: EC2SelfTaggingPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateTags
                  - ec2:DescribeTags
                Resource: '*'
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-ec2-role'

  # Instance Profile for EC2
  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: !Sub '${AWS::StackName}-ec2-instance-profile'
      Roles:
        - !Ref EC2Role

  # Lambda Role for Auto-Tagging
  LambdaTaggingRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${AWS::StackName}-lambda-tagging-role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: EC2TaggingPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:CreateTags
                  - ec2:DescribeInstances
                Resource: '*'

  # Lambda Function for Auto-Tagging
  AutoTaggingFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-auto-tagging'
      Runtime: python3.11
      Handler: index.lambda_handler
      Role: !GetAtt LambdaTaggingRole.Arn
      Timeout: 60
      Code:
        ZipFile: |
          import boto3
          import json

          def lambda_handler(event, context):
              ec2 = boto3.client('ec2')

              # Extract instance ID from EventBridge event
              instance_id = event['detail']['instance-id']

              # Get instance details
              response = ec2.describe_instances(InstanceIds=[instance_id])
              instance = response['Reservations'][0]['Instances'][0]

              # Get AZ and determine hostname
              az = instance['Placement']['AvailabilityZone']

              hostname_map = {
                  'ap-northeast-1a': 'pochub-001',
                  'ap-northeast-1c': 'pochub-002',
                  'ap-northeast-1d': 'pochub-003'
              }

              hostname = hostname_map.get(az, 'pochub-unknown')

              # Create tags
              ec2.create_tags(
                  Resources=[instance_id],
                  Tags=[
                      {'Key': 'Name', 'Value': hostname},
                      {'Key': 'Hostname', 'Value': hostname}
                  ]
              )

              return {
                  'statusCode': 200,
                  'body': json.dumps(f'Tagged instance {instance_id} with hostname {hostname}')
              }

  # EventBridge Rule for EC2 Instance Launch
  EC2LaunchRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub '${AWS::StackName}-ec2-launch-rule'
      Description: 'Trigger Lambda when EC2 instance launches'
      EventPattern:
        source:
          - aws.ec2
        detail-type:
          - EC2 Instance State-change Notification
        detail:
          state:
            - running
          instance-id:
            - prefix: !Sub 'i-'
      State: ENABLED
      Targets:
        - Arn: !GetAtt AutoTaggingFunction.Arn
          Id: AutoTaggingTarget

  # Permission for EventBridge to invoke Lambda
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AutoTaggingFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt EC2LaunchRule.Arn

  # Launch Template for Auto Scaling Group
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub '${AWS::StackName}-launch-template'
      LaunchTemplateData:
        # Latest Amazon Linux 2023 AMI
        ImageId: '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-6.1-x86_64}}'
        InstanceType: !Ref InstanceType
        KeyName: !If [HasKeyPair, !Ref KeyPairName, !Ref 'AWS::NoValue']
        IamInstanceProfile:
          Arn: !GetAtt EC2InstanceProfile.Arn
        SecurityGroupIds:
          - !Ref SecurityGroupId
        # Simple UserData for monitoring setup only
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y

            # Install CloudWatch Agent
            wget https://s3.amazonaws.com/amazoncloudwatch-agent/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm
            rpm -U ./amazon-cloudwatch-agent.rpm

            # Configure CloudWatch Agent
            cat > /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json << 'EOF'
            {
              "metrics": {
                "namespace": "POC/EC2Instances",
                "metrics_collected": {
                  "cpu": {
                    "measurement": ["cpu_usage_idle", "cpu_usage_user", "cpu_usage_system"],
                    "metrics_collection_interval": 60
                  },
                  "mem": {
                    "measurement": ["mem_used_percent"],
                    "metrics_collection_interval": 60
                  },
                  "disk": {
                    "measurement": ["used_percent"],
                    "metrics_collection_interval": 60,
                    "resources": ["*"]
                  }
                }
              },
              "logs": {
                "logs_collected": {
                  "files": {
                    "collect_list": [
                      {
                        "file_path": "/var/log/messages",
                        "log_group_name": "/aws/ec2/poc-system/messages",
                        "log_stream_name": "{instance_id}"
                      }
                    ]
                  }
                }
              }
            }
            EOF

            # Start CloudWatch Agent
            /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl \
                -a fetch-config \
                -m ec2 \
                -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json \
                -s

            # インスタンス起動時に自身のAZ名を取得し、タグ付与（IMDSv2対応）
            TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600" 2>/dev/null)
            AZ=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" -s http://169.254.169.254/latest/meta-data/placement/availability-zone)
            INSTANCE_ID=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" -s http://169.254.169.254/latest/meta-data/instance-id)

            # 変数が正しく取得できた場合のみタグ付与
            if [ -n "$INSTANCE_ID" ] && [ -n "$AZ" ]; then
              aws ec2 create-tags --resources $INSTANCE_ID --tags Key=AvailabilityZone,Value=$AZ --region ap-northeast-1
            else
              echo "Failed to retrieve INSTANCE_ID or AZ from metadata service"
            fi        # Monitoring
        Monitoring:
          Enabled: true

        # Tags for instances
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Application
                Value: !Ref ApplicationName
              - Key: Environment
                Value: !Ref Environment
              - Key: PatchGroup
                Value: !Sub '${Environment}-ec2-instances'
              - Key: SSMManaged
                Value: 'true'
          - ResourceType: volume
            Tags:
              - Key: Name
                Value: !Sub '${ApplicationName}-${Environment}-volume'
              - Key: Application
                Value: !Ref ApplicationName
              - Key: Environment
                Value: !Ref Environment

  # Auto Scaling Group
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub '${AWS::StackName}-asg'
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MinSize: !Ref DesiredCapacity
      MaxSize: !Ref DesiredCapacity
      DesiredCapacity: !Ref DesiredCapacity
      VPCZoneIdentifier: !Ref PrivateSubnets
      HealthCheckType: ELB
      HealthCheckGracePeriod: 300
      TargetGroupARNs:
        - !Ref TargetGroupArn
      # Instance distribution across AZs
      AvailabilityZones:
        - ap-northeast-1a
        - ap-northeast-1c
        - ap-northeast-1d
      Tags:
        - Key: Name
          Value: !Sub '${ApplicationName}-${Environment}-asg'
          PropagateAtLaunch: false
        - Key: Application
          Value: !Ref ApplicationName
          PropagateAtLaunch: true
        - Key: Environment
          Value: !Ref Environment
          PropagateAtLaunch: true

  # CloudWatch Log Groups for EC2 logs
  SystemMessagesLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/ec2/poc-system/messages
      RetentionInDays: 14

Outputs:
  EC2SecurityGroupId:
    Description: EC2 instance Security Group ID
    Value: !Ref SecurityGroupId
    Export:
      Name: poc-ec2-sg-id
  AutoScalingGroupName:
    Description: Auto Scaling Group Name
    Value: !Ref AutoScalingGroup
    Export:
      Name: !Sub '${AWS::StackName}-asg-name'

  LaunchTemplateId:
    Description: Launch Template ID
    Value: !Ref LaunchTemplate
    Export:
      Name: !Sub '${AWS::StackName}-launch-template-id'

  EC2RoleArn:
    Description: EC2 IAM Role ARN
    Value: !GetAtt EC2Role.Arn
    Export:
      Name: !Sub '${AWS::StackName}-ec2-role-arn'

  LambdaFunctionArn:
    Description: Auto-tagging Lambda Function ARN
    Value: !GetAtt AutoTaggingFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-lambda-arn'
