---

- name: Make directories 
  file: path={{ item }} state=directory owner=root group=root 
  loop:
    - /db0
    - /db0/log

- name: Make a directory 
  file: path={{ item }} state=directory owner=tomcat group=tomcat 
  loop:
    - /db0/log/app

- name: Link /var/log/app -> /db0/log/app
  file:
    state: link
    src: /db0/log/app
    dest: /var/log/app
  when: not ansible_check_mode

- name: Make directories
  file: path={{ item.dir }} state=directory owner={{ item.owner }} group={{ item.group }} 
  loop:
    - { dir: /usr/local/app, owner: tomcat, group: tomcat }
    - { dir: /usr/local/app/gbs, owner: gooidc, group: gooidc }
  when: server_role == "hlp"

- name: Make directories
  file: path={{ item }} state=directory owner=gooscp group=gooscp 
  loop:
    - /usr/local/app
    - /usr/local/app/gbs
  when: server_role == "edb"

- name: Make directories
  file: path={{ item }} state=directory owner=tomcat group=tomcat 
  loop:
    - /var/log/app/gbs
    - /var/log/app/gbs/gbs

- name: Make /var/log/app/gbs/gbs_mule
  file: path={{ item }} state=directory owner=gooidc group=gooidc 
  loop:
    - /var/log/app/gbs/gbs_mule

- name: ダウンロード {{ mule_filename }}
  get_url:
    url: "{{ remote_repo_url }}/{{ mule_filename }}"
    dest: /tmp/{{ mule_filename }}
    use_proxy: yes

- name: gbs_muleが既にインストール済みか確認
  stat:
    path: /usr/local/app/gbs/mule-standalone-2.2.1
  register: mule_pkg

# gbs_muleがインストールされてなければインストール
- name: Unarchive {{ mule_filename }}
  unarchive:
    src: /tmp/{{ mule_filename }}
    dest: /usr/local/app/
    owner: gooidc
    group: gooidc
    remote_src: yes
  when: mule_pkg.stat.exists == false

- name: mule-config.xmlを配布
  template:
    src: templates/mule/{{ server_role }}/mule-config.xml.j2
    dest: /usr/local/app/gbs/gbs_mule/conf/mule-config.xml
    owner: gooidc
    group: gooidc
    mode: 0644
  notify:
    - gbs_mule_restart_msg

- name: Copy gbs_mule.service
  template:
    src: templates/mule/gbs_mule.service.j2
    dest: /etc/systemd/system/gbs_mule.service
    backup: yes 
    owner: root
    group: root

# mule用 KeyStoreファイル
#   2023-04-24
#     この jks (Java Key Store) が対向先 www.chocom.net のSSL証明書 "DigiCert" に対応していないため、
#     毎月24日の「カード有効期限切れ警告対象者を抽出するプログラム」「PreOrderCheck.sh」にて、SSL接続できない旨の大量エラーが発生。
#     ⇒ この類いのエラーが出たときは、keytoolコマンドによって本資材ファイルの更新が必要。
#       
#       com.sun.jersey.api.client.ClientHandlerException: javax.net.ssl.SSLHandshakeException:sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`
#
#     詳細な手順はこちらを参照してください。
#       Gbs muleのjavakeystore追加手順 - 共通業務 - ID課金チーム
#       https://ticket.id001.goo.ne.jp/projects/idsvc/wiki/Gbs_mule%E3%81%AEjavakeystore%E8%BF%BD%E5%8A%A0%E6%89%8B%E9%A0%86
- name: gbs_mule.jks を配布する
  copy:
    src: files/gbs_mule.jks
    dest: /usr/local/app/gbs/gbs_mule/conf/gbs_mule.jks
    owner: gooidc
    group: gooidc
    mode: 0644
