---
# httpd_idc_webを最初に実行する。
# phpとか他のパッケージが/var/log/httpdを作成する前に、httpd_idc_webで/var/log/httpdをシンボリックリンクにする
- hosts: gooid_web
  become: yes
  environment: "{{ proxy_env }}"
  roles:
    - { role: httpd_idc_web, tags: httpd_idc_web }
    - { role: jdk, tags: jdk }
    - { role: common, tags: common }
    - { role: php, tags: php }
    - { role: gbss_app, tags: gbss_app }
    - { role: proxysql, tags: proxysql }
    - { role: mariadb_client, tags: mariadb_client }
    - { role: httpd_gbs_web, tags: httpd_gbs_web }
    - { role: tomcat_web, tags: tomcat_web }
    - { role: monitoring_web, tags: monitoring_web }
    - { role: rbash, tags: rbash }
    - { role: extend-acl, tags: extend-acl}
# tomcatの設定を修正する前にtomcatを停止。起動中に設定ファイルを配布するとtomcatがエラーを発生して停止する可能性がある。
  pre_tasks:
    - name: tomcatの停止
      block:
        - systemd:
            name: tomcat_idc
            state: stopped
      rescue:
        - debug:
            msg: "tomcatの停止に失敗しました。tomcat停止処理をスキップします。"
      tags:
        - tomcat_web

  post_tasks:
    - name: tomcat起動コマンドの表示
      debug:
        msg: "{{ commands }}"
      tags:
        - tomcat_web

  vars:
    commands:
      - "  注意：tomcatは停止しています。手動で起動してください。 "
      - "  sudo systemctl restart tomcat_idc  "
      - "  sudo systemctl status tomcat_idc   "

