---
- hosts: gooid_edb
  become: yes
  environment: "{{ proxy_env }}"
  roles:
    - { role: common, tags: common }
    - { role: perl, tags: perl }
    - { role: proxysql, tags: proxysql }
    - { role: jdk, tags: jdk }
    - { role: gbs_mule, tags: gbs_mule }
    - { role: mariadb_server, tags: mariadb_server }
    - { role: httpd_edb, tags: httpd_edb }
    - { role: tomcat_edb, tags: tomcat_edb }
    - { role: db_backup, tags: db_backup }
    - { role: rbash, tags: rbash }
    - { role: extend-acl, tags: extend-acl}

# tomcatの設定を修正する前にtomcatを停止。起動中に設定ファイルを配布するとtomcatがエラーを発生して停止する可能性がある。
  pre_tasks:
    - name: tomcatの停止
      block:
        - systemd:
            name: tomcat
            state: stopped
      rescue:
        - debug:
            msg: "tomcatの停止に失敗しました。tomcat停止処理をスキップします。"
      tags:
        - tomcat_edb

  post_tasks:
    - name: tomcat起動コマンドの表示
      debug:
        msg: "{{ commands }}"
      tags:
        - tomcat_edb

  vars:
    commands:
      - "  注意：tomcatは停止しています。手動で起動してください。 "
      - "  sudo systemctl restart tomcat  "
      - "  sudo systemctl status tomcat   "

