---
- hosts: gooid_log
  become: yes
  environment: "{{ proxy_env }}"
  roles:
    - { role: common, tags: common }
    - { role: ant, tags: ant }
    - { role: maven, tags: maven }
    - { role: jdk, tags: jdk }
    - { role: git, tags: git }
    - { role: td-agent, tags: td-agent }
    - { role: pdsh, tags: pdsh }
    - { role: rbash, tags: rbash }
    - { role: extend-acl, tags: extend-acl}
