---
- import_role:
    name: mod_ldap

- import_role:
    name: mod_ssl

- import_role:
    name: httpd

- import_role:
    name: mod_gooaes
  when: not inventory_hostname_short is regex("^idhub-\d{2}")

# idhubには不要なのでインストールしない
- import_role:
    name: mod_security
  when: not inventory_hostname_short is regex("^idhub-\d{2}")
