--- 
- name: Copy httpd_idc.service
  template:
    src: templates/httpd/httpd_idc.service.j2
    dest: /etc/systemd/system/httpd_idc.service
    backup: yes 
    owner: puppet
    group: puppet
    mode: 0644

# httpd.confの配布 release_env = "pro" または "dev"
- name: Copy httpd.conf
  template:
    src: templates/httpd/httpd.conf-{{ release_env }}.j2
    dest: /etc/httpd/conf/httpd.conf
    backup: yes 
    owner: root
    group: root
    mode: 0644
  notify:
    - httpd_idc_web_restart_msg

- name: Copy rewrite.conf 
  template:
    src: templates/httpd/rewrite.conf.j2
    dest: /etc/httpd/conf/rewrite.conf
    backup: yes
    owner: root
    group: root
    mode: 0644
  notify:
    - httpd_idc_web_restart_msg

- name: Copy external-maintenance.conf 
  template:
    src: templates/httpd/external-maintenance.conf.j2
    dest: /etc/httpd/conf/external-maintenance.conf
    backup: yes
    owner: root
    group: root
    mode: 0644
  notify:
    - httpd_idc_web_restart_msg

# aclは商用環境のみ配置
# 検証環境はrproxyでIP制限をかける
# 2023/5/26よりaclはgooidとidhubで分ける
- name: Copy acl-servers.conf
  template:
    src: templates/httpd/acl-servers.conf-{{ service_type }}-{{ release_env }}.j2
    dest: /etc/httpd/conf/acl-servers.conf
    backup: yes
    owner: root
    group: root
    mode: 0644
  when: release_env == "pro"
  notify:
    - httpd_idc_web_restart_msg
    
- name: Copy http.conf
  # roles/katemusha/templates に値を設定します。
  vars:
    kagemusha_port: "{{ httpd_idc_port }}"
  template:
    src: templates/httpd/{{ httpd_idc_http_conf_template }}
    dest: /etc/httpd/conf.d/{{ httpd_idc_http_conf }}
    backup: yes
    owner: root
    group: root
    mode: 0644
  notify:
    - httpd_idc_web_restart_msg
    
- name: Copy p3p.conf
  template:
    src: templates/httpd/p3p.conf.j2
    dest: /etc/httpd/conf.d/p3p.conf
    backup: yes
    owner: root
    group: root
    mode: 0644
  notify:
    - httpd_idc_web_restart_msg

# gooidにだけ配布する
# reCAPTCHA用のファイル
- name: Copy mod_security.conf
  template:
    src: templates/httpd/mod_security.conf.j2
    dest: /etc/httpd/conf.d/mod_security.conf
    backup: yes
    owner: root
    group: root
    mode: 0644
  when: inventory_hostname_short is regex("gooid-\d{2}")
  notify:
    - httpd_idc_web_restart_msg

# reCAPTCHA用のファイル
- name: Copy ipaddress_white_list.txt
  template:
    src: templates/httpd/ipaddress_white_list.txt.j2
    dest: /etc/httpd/conf.d/ipaddress_white_list.txt
    backup: yes
    owner: root
    group: root
    mode: 0644

# gooidにだけ配布する
# reCAPTCHA用のファイル
- name: Copy geo.mysql.lua
  template:
    src: templates/httpd/geo.mysql.lua.j2
    dest: /etc/httpd/conf.d/geo.mysql.lua
    backup: yes
    owner: root
    group: root
    mode: 0644
  when: inventory_hostname_short is regex("gooid-\d{2}")

# reCAPTCHA用のファイル
- name: Copy countrycode_gray_list.txt
  template:
    src: templates/httpd/countrycode_gray_list.txt.j2
    dest: /etc/httpd/conf.d/countrycode_gray_list.txt
    backup: yes
    owner: root
    group: root
    mode: 0644

- name: Copy testtools.conf
  template:
    src: templates/httpd/testtools.conf.j2
    dest: /etc/httpd/conf.d/testtools.conf 
    backup: yes
    owner: root
    group: root
    mode: 0644
  when: release_env == "dev"
  notify:
    - httpd_idc_web_restart_msg

- name: Copy 00-base.conf
  template:
    src: templates/httpd/00-base.conf.j2
    dest: /etc/httpd/conf.modules.d/00-base.conf 
    backup: yes
    owner: root
    group: root
    mode: 0644

- name: Copy 00-mpm.conf
  template:
    src: templates/httpd/00-mpm.conf.j2
    dest: /etc/httpd/conf.modules.d/00-mpm.conf 
    backup: yes
    owner: root
    group: root
    mode: 0644

- name: Copy 00-proxy.conf
  template:
    src: templates/httpd/00-proxy.conf.j2
    dest: /etc/httpd/conf.modules.d/00-proxy.conf 
    backup: yes
    owner: root
    group: root
    mode: 0644

# gooidにだけ配布する
# mod_gooaes用のファイルを配布
- name: Copy gooaes.conf
  template:
    src: templates/httpd/gooaes.conf.j2
    dest: /etc/httpd/conf.d/gooaes.conf
    owner: root
    group: root
    mode: 0644
  when: inventory_hostname_short is regex("^gooid-\d{2}")
  notify:
    - httpd_idc_web_restart_msg

# mod_gooaesロギング用ファイルを配布
- name: Copy libgooid.conf
  copy:
    src: files/rsyslog/libgooid.conf
    dest: /etc/rsyslog.d/libgooid.conf
    owner: root
    group: root
    mode: 0644
  when: inventory_hostname_short is regex("^gooid-\d{2}")
  notify:
    - rsyslog_restarted

# mod_gooaes用定義を追記したconfigファイルを配布
- name: Copy rsyslog.conf
  copy:
    src: files/rsyslog/rsyslog.conf
    dest: /etc/rsyslog.conf
    owner: root
    group: root
    mode: 0644
  when: inventory_hostname_short is regex("^gooid-\d{2}")
  notify:
    - rsyslog_restarted

- name: sysconfig-httpdの存在を確認
  stat:
    path: /etc/sysconfig/httpd
  register: httpd

- name: Copy sysconfig-httpd
  template:
    src: files/sysconfig/httpd.j2
    dest: /etc/sysconfig/httpd 
    backup: yes
    owner: root
    group: root
    mode: 0644
  when: not httpd.stat.exists
