template_path: dkim-manager-lambda.yaml

parameters:
  ProjectName: !stack_output prod/phase-1-infrastructure-foundation.yaml::ProjectName
  Environment: !stack_output prod/phase-1-infrastructure-foundation.yaml::Environment
  DKIMManagerRoleArn: !stack_output prod/phase-1-infrastructure-foundation.yaml::DKIMManagerRoleArn
  DKIMConfigSecretArn: !stack_output prod/phase-1-infrastructure-foundation.yaml::DKIMConfigSecretArn
  DKIMCertificatesBucketName: !stack_output prod/phase-1-infrastructure-foundation.yaml::DKIMCertificatesBucketName
  DKIMEncryptionKeyArn: !stack_output prod/phase-1-infrastructure-foundation.yaml::DKIMEncryptionKeyArn
  LambdaRuntime: "python3.13"
  CertificateValidityDays: 2  # 2 days validity for testing (production: 456 days)
  RenewalAlertDays: 1          # Test mode: Alert 1 day before expiration (production: 60 days for DNS coordination)
  DKIMSeparator: "gooid-21-pro" # Fixed value for prod environment

  # BYODKIM Safety Control Parameters
  BYODKIMAutoApplyToSES: "false"           # 新鍵をSESに自動適用しない
  BYODKIMRotationMode: "MANUAL"            # 手動制御モード
  DNSTeamNotificationEmail: "goo-idpay-sys@ml.nttdocomo.com"  # DNS担当者への通知

dependencies:
  - prod/phase-1-infrastructure-foundation.yaml

tags:
  Phase: "2-v2"
  Component: "DKIM-Manager-V2"
  Implementation: "AWS-Official-OpenSSL"
