# Phase 3: SES Configuration and BYODKIM Initialization Phase
# Steps 11-13: SES Email Identity creation, BYODKIM setup, DKIM token generation

template_path: ses-configuration.yaml

parameters:
  ProjectName: !stack_output prod/phase-1-infrastructure-foundation.yaml::ProjectName
  Environment: !stack_output prod/phase-1-infrastructure-foundation.yaml::Environment
  DomainName: !stack_output prod/phase-1-infrastructure-foundation.yaml::DomainName
  DKIMManagerFunctionArn: !stack_output prod/phase-2-dkim-system.yaml::DKIMManagerFunctionArn
  DKIMSeparator: gooid-21-prod

  # SES Security Parameters
  SESAllowedIPs:
    - "202.217.75.82/31"          # 商用環境IP範囲
    - "202.217.75.84/30"          # 商用環境IP範囲
    # - "202.217.75.98/32"      # 開発環境IP範囲

  EnableSESIPFiltering: "true"    # IP制限を有効化（"false"で無効化）

  # SES Monitoring Parameters
  BounceRateThreshold: 5.0        # バウンス率アラーム閾値（%）- 5%で警告
  ComplaintRateThreshold: 0.1     # 苦情率アラーム閾値（%）- 0.1%で警告
  EnableSESMonitoring: "true"     # SESモニタリング有効化（"false"で無効化）
  SESAlarmSNSTopicArn: "arn:aws:sns:ap-northeast-1:007773581311:aws-ses-migration-prod-notifications"  # base.yamlのSNSトピックを手動指定
  CloudWatchLogRetentionDays: 90  # CloudWatchログ保持期間（日）

  # Feature Flags - SES Core Functions
  EnableBounceComplaintHandling: "true"    # バウンス・苦情の自動処理有効化
  EnableDKIM: "true"                       # DKIM署名有効化（BYODKIMには必須）
  EnableDomainVerification: "true"         # ドメイン検証プロセス有効化
  EnableBYODKIMAutomation: "false"         # BYODKIM自動化（DNS調整のため無効）

  # BYODKIM Safety Configuration - DNS協調制御
  BYODKIMRotationMode: "MANUAL"            # MANUAL: DNS登録完了確認後に手動実行
  BYODKIMDNSConfirmationRequired: "true"   # DNS登録確認必須（メール認証失敗防止）
  BYODKIMRotationNotificationEmail: "goo-idpay-sys@ml.nttdocomo.com"  # DNS調整担当への通知

  # Feature Flags - Regional and Japanese-specific Features
  EnableTokyoRegionFeatures: "true"        # 東京リージョン固有機能（レイテンシ最適化）
  EnableJapaneseCompliance: "true"         # 日本法規制対応（個人情報保護法等）
  EnableTokyoSES: "false"                  # 東京SES固有ルーティング（本番環境では無効）
  EnableJapaneseEmailTemplates: "true"     # 日本語メールテンプレート最適化

  # SES Metrics Configuration
  CloudWatchMetricNamespace: "ses-migration/prod/SES"  # SES専用メトリクス名前空間

  # 【大阪リージョン対応メモ】
  # 大阪リージョン（ap-northeast-3）使用時は以下を変更：
  # - EnableTokyoRegionFeatures → "false"
  # - EnableOsakaRegionFeatures → "true" （新規パラメータ追加が必要）
  # - CloudWatchMetricNamespace → "ses-migration/prod/osaka/SES"

dependencies:
  - prod/phase-1-infrastructure-foundation.yaml
  - prod/phase-2-dkim-system.yaml

tags:
  Phase: "3-ses-byodkim"
  Purpose: "SES configuration and BYODKIM initialization"
  Environment: prod
